### ISSUE TITLE
Issues adding the Docker container to unraid

### ISSUE THREAD

**Issue by MiranoVerhoef** [matt8707/ha-fusion#1]
Hello,

I just saw your post on Reddit and i had to try this beautiful layout, so thank your for making this first of all!
(Send you a little PayPal to support the creation and further development)

I added the container based on your docker-compose file but it seems like i'm missing a repository:

![image](https://github.com/matt8707/ha-fusion/assets/67699857/39aa7fad-1b2a-4c90-8a40-87e1df5af210)

Would you be able to give me the correct repository:

![image](https://github.com/matt8707/ha-fusion/assets/67699857/9903016e-0685-4ed9-b959-2abbcfa0a888)

Thank you!

**Comment by MiranoVerhoef** [comment]
Getting this error:

docker: Error response from daemon: pull access denied for matt8707/ha-fusion, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by MiranoVerhoef** [comment]
Got it working for now with building my own docker. Can't wait for the addon version. That'd be the strength of this !

**Comment by Holewijn** [comment]
> Got it working for now with building my own docker. Can't wait for the addon version. That'd be the strength of this !

Could you share your docker setup so i can try it on unRaid 😀

**Comment by MiranoVerhoef** [comment]
Sure i can, ready?

1. make a directory for the docker
2. git clone: `git clone https://github.com/matt8707/ha-fusion.git`
3. CD into the ha-fusion folder
4. use the following ocmmand to build the docker: `docker build .`
5. wait for it to finish
6. check for the newest image id with `docker image ls`
7. now go to docker and create a new container with the following settings:
(Wehre Repository is the docker image id from step 6)
![image](https://github.com/matt8707/ha-fusion/assets/67699857/b11fc707-bc97-439c-836f-f388188088f0)

Now it should work :)

**Comment by MiranoVerhoef** [comment]
> > Got it working for now with building my own docker. Can't wait for the addon version. That'd be the strength of this !
> 
> Could you share your docker setup so i can try it on unRaid 😀

Looks like you got lucky. Skip all my steps i just wrote. This template works out of the box. **Thank you @matt8707 !**

![image](https://github.com/matt8707/ha-fusion/assets/67699857/79b58fe7-ce06-4291-8957-8160801a58e0)

**Comment by MiranoVerhoef** [comment]
Meanwhile i'm working to add it to the unraid community apps. but that will take a bit of time :)

**Comment by MiranoVerhoef** [comment]
@Holewijn @matt8707 

I've submitted a request for ha-fusion to get integrated into unraid ca's template area. Once it is available, I'll let it know.

**Comment by matt8707** [comment]
Thanks, both `docker pull ghcr.io/matt8707/ha-fusion` and addon should work now!

**Comment by MiranoVerhoef** [comment]
> Thanks, both `docker pull ghcr.io/matt8707/ha-fusion` and addon should work now!

Thank you so much for your work. Im sure you got a lot you want to add. These options beneath is what i thought of would make it so amazing:

1. Home assistant addon is working, but i would love to see a option to have a direct link to it as well, instead of the ingress
2. a option to lock down settings with a password so not everyone can edit it


Again thank you for your work and merry christmas :)

**Comment by MiranoVerhoef** [comment]
Ha-fusion is now available on unraid apps section. @Holewijn you should be able to install it that way.

@matt8707 for your information I’ve submitted a template which states what evoirement tables is needed for it to run. So now it’s way easier for unraid users to install it. :)

happy holidays all!
