### ISSUE TITLE
Add-on is not loading

### ISSUE THREAD

**Issue by tomerbs** [matt8707/ha-fusion#10]
Hi,

After installing the add-on, it`s not loading at startup,
and when I'm trying to load it manually, I get this error message:
![image](https://github.com/matt8707/ha-fusion/assets/33035719/6c19b8de-17c1-4c3f-86b0-3ae7cbb1d3cf)

Please tell me how to solve this.
Thanks.

**Comment by matt8707** [comment]
Have you tried rebuilding? Wait for it to build on your system

![screen](https://github.com/matt8707/ha-fusion/assets/36163594/7d7ad3d4-1eac-41e5-a80b-bb1b104d02ba)

**Comment by tomerbs** [comment]
Yes, I'm on version 2023.12.4
Are there any additional prerequisites I need to install?
I'm trying to rebuild it and will update

**Comment by matt8707** [comment]
Nope, if you rebuild it should pull latest from https://github.com/matt8707/ha-fusion and haos builds the image

**Comment by tomerbs** [comment]
When trying to rebuild I've got this error:
![image](https://github.com/matt8707/ha-fusion/assets/33035719/a1f5873c-0beb-4783-9d39-a923afa1fa37)

**Comment by matt8707** [comment]
run `ha supervisor logs` and post the errors here

**Comment by tomerbs** [comment]
This is the log:
[core-ssh ~]$ ha supervisor logs
2:13:15 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelecte@3.17.2
svelte-tiny-virtual-list@2.0.5

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

vite v5.0.10 building SSR bundle for production...

transforming...

2:13:49 PM [vite-plugin-svelte] /rootfs/node_modules/svelecte/src/components/Control.svelte:96:0 A11y: <div> with mousedown handler must have an ARIA role

94: </script>
95:
96: <div class="sv-control" class:is-active={$hasFocus} class:is-disabled={disabled}
    ^
97: on:mousedown={focusControl}
98: >

2:13:49 PM [vite-plugin-svelte] /rootfs/node_modules/svelecte/src/components/Dropdown.svelte:239:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by a keyboard event handler. Consider whether an interactive element such as <button type="button"> or <a> might be more appropriate. See https://svelte.dev/docs/accessibility-warnings#a11y-click-events-have-key-events for more details.

237:   {#if inputValue && creatable && !maxReached}
238:     <div class="creatable-row-wrap">
239:       <div class="creatable-row" on:click={dispatch('select', inputValue)} on:mouseenter={dispatch('hover', listIndex.last)}
           ^
240:         class:active={currentListLength == dropdownIndex}
241:         class:is-disabled={alreadyCreated.includes(inputValue)}

2:13:49 PM [vite-plugin-svelte] /rootfs/node_modules/svelecte/src/components/Dropdown.svelte:239:6 A11y: <div> with click, mouseenter handlers must have an ARIA role

237:   {#if inputValue && creatable && !maxReached}
238:     <div class="creatable-row-wrap">
239:       <div class="creatable-row" on:click={dispatch('select', inputValue)} on:mouseenter={dispatch('hover', listIndex.last)}
           ^
240:         class:active={currentListLength == dropdownIndex}
241:         class:is-disabled={alreadyCreated.includes(inputValue)}

2:13:49 PM [vite-plugin-svelte] /rootfs/node_modules/svelecte/src/components/Dropdown.svelte:174:0 A11y: <div> with mousedown handler must have an ARIA role

172:
173: {#if isMounted && renderDropdown}
174: <div class="sv-dropdown" class:is-virtual={virtualList} aria-expanded={$hasDropdownOpened}
     ^
175:   on:mousedown|preventDefault
176: >

2:13:49 PM [vite-plugin-svelte] /rootfs/node_modules/svelecte/src/components/Item.svelte:19:0 A11y: <div> with mousedown handler must have an ARIA role

17:
18: {#if item.$isGroupHeader}
19: <div class="optgroup-header" on:mousedown|preventDefault><b>{item.label}</b></div>
    ^
20: {:else}
21: <div class="sv-item"

✓ 363 modules transformed.

rendering chunks...

2:14:17 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelecte@3.17.2
svelte-tiny-virtual-list@2.0.5

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

vite v5.0.10 building for production...

transforming...

npm ERR! path /rootfs
npm ERR! command failed
npm ERR! signal SIGKILL
npm ERR! command sh -c vite build


npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-26T14_13_03_480Z-debug-0.log

Removing intermediate container 2105ce87e637

23-12-26 16:19:51 INFO (SyncWorker_2) [supervisor.docker.manager] Restarting homeassistant
23-12-26 16:20:14 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-12-26 16:20:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-12-26 16:20:48 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
23-12-26 16:20:49 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-12-26 16:20:50 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-12-26 16:20:56 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/matt8707/addon-ha-fusion repository
23-12-26 16:20:56 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-12-26 16:20:56 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-12-26 16:20:57 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-12-26 16:20:57 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-12-26 16:21:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-12-26 16:21:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-12-26 16:21:38 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to STARTING
23-12-26 16:21:46 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
23-12-26 16:21:46 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-12-26 16:21:54 ERROR (SyncWorker_4) [supervisor.docker.manager] Image 65f67727/aarch64-addon-ha_fusion:2023.12.4 does not exist for addon_65f67727_ha_fusion
23-12-26 16:22:17 ERROR (SyncWorker_5) [supervisor.docker.manager] Image 65f67727/aarch64-addon-ha_fusion:2023.12.4 does not exist for addon_65f67727_ha_fusion
23-12-26 16:22:33 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from core_ssh

**Comment by tomerbs** [comment]
I forgot to mention this is a fresh install of HA on RP3.
I tried to clear the browser cache and rebuild the add-on again and this time I've got this error:
![image](https://github.com/matt8707/ha-fusion/assets/33035719/91e62d6c-b8c4-41fb-a246-f72f67a41c32)

**Comment by matt8707** [comment]
There's an error when building
```
npm ERR! path /rootfs
npm ERR! command failed
npm ERR! signal SIGKILL
npm ERR! command sh -c vite build
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-26T14_13_03_480Z-debug-0.log
Removing intermediate container 2105ce87e637
 ```

can you run
```bash
cat /root/.npm/_logs/2023-12-26T14_13_03_480Z-debug-0.log
```

**Comment by tomerbs** [comment]
[core-ssh ~]$ cat /root/.npm/_logs/2023-12-26T14_13_03_480Z-debug-0.log
cat: can't open '/root/.npm/_logs/2023-12-26T14_13_03_480Z-debug-0.log': No such file or directory

**Comment by matt8707** [comment]
Okay, I have a rpi3 around here somewhere so I can test later

**Comment by tomerbs** [comment]
After Rebuild failed and system rebooted, I tried to run the add-on again and now get this error:
![image](https://github.com/matt8707/ha-fusion/assets/33035719/e0af0553-fe62-4ce6-a1f1-8a68da6437d0)

**Comment by matt8707** [comment]
Yes, the image is removed when build fails here `Removing intermediate container 2105ce87e637`

**Comment by matt8707** [comment]
I couldn't build it either.. so I've moved the build stage to github, try 2023.12.5

https://github.com/matt8707/ha-fusion/releases/tag/2023.12.5

**Comment by tomerbs** [comment]
Ok, After I updated to version 2023.12.5 it now working.
Thanks.
