### ISSUE TITLE
24/12hr Clock bug

### ISSUE THREAD

**Issue by simonhills** [matt8707/ha-fusion#104]
Hi, absolutely love the direction of this.

Minor bug, the side bar clock doesn't work properly in 12hr format. As you can see, it displays 00:XXpm, rather than 12:XXpm.

![12hr](https://github.com/matt8707/ha-fusion/assets/61353959/1dd6d0fd-19d6-4a1f-be65-af3b7f14f4a4)
![24hr](https://github.com/matt8707/ha-fusion/assets/61353959/780f4797-9916-455c-9c9a-62740fd7aac7)
![12hr 2](https://github.com/matt8707/ha-fusion/assets/61353959/32c4ad50-f423-4d72-983a-5c6ad4e2aee2)

Also shows 01:00pm, technically a 12hr clock should only have the active digits, ie 1:00pm.

Cheers

**Comment by matt8707** [comment]
I think https://github.com/matt8707/ha-fusion/commit/fec9558bc092bc8386c02dbe7792d6bf4363c740 will adress this, if not please open a new issue

**Comment by JigSawFr** [comment]
We the same with 24h format

**Comment by matt8707** [comment]
> Was the same with 24h format

What do you mean?

**Comment by JigSawFr** [comment]
> > Was the same with 24h format
> 
> 
> 
> What do you mean?

At midnight, we see 24:35 instead of 00:35
