### ISSUE TITLE
env HASS_URL undefined

### ISSUE THREAD

**Issue by nagtegaal** [matt8707/ha-fusion#105]
I installed ha-fusion as an add-on in HA. The logbook says 
`env HASS_URL undefined`

The installation instructions, do not say anything about this, or where to set this.
How can I get rid of this error and where do I need to put this? Shouldn't the documentation say something about this?

**Comment by matt8707** [comment]
This can be ignored, as HASS_URL is not used when using the addon, and therefore it's undefined. Keep in mind that ha-fusion is still in pre-beta.
