### ISSUE TITLE
FR: Sidebar timer name

### ISSUE THREAD

**Issue by schumi2309** [matt8707/ha-fusion#107]
Good morning,
What would be great is to be able to put text in the sidebar for example after a separation.
Would it be possible to add it in the next update?
Great job!

**Comment by joe-heaton** [comment]
You can add permanent/non-changing text via Templates but I'm not sure if you're referring to the ability to add a Heading?

**Comment by schumi2309** [comment]
I put counts in my sidebar, and I would have liked to put a title on each count...

![Capture d’écran 2024-01-06 à 17 12 49](https://github.com/matt8707/ha-fusion/assets/47976917/871f3f9b-ab42-4dbc-994a-108b6ce2bee6)

**Comment by matt8707** [comment]
Ah, a title/name option for timers to distinguish them, that's reasonable
