### ISSUE TITLE
Error: ENOENT on 2023.12.4

### ISSUE THREAD

**Issue by briiiian** [matt8707/ha-fusion#11]
I upgrade addon to 2023.12.4 bug it does't work.
my ha info:
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

addon log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
Listening on 0.0.0.0:5050
Error reading or parsing ./data/configuration.yaml: Error: ENOENT: no such file or directory, open './data/configuration.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-zNUOnAaM.js:8:18)
    at async Promise.all (index 0)
    at async load (file:///rootfs/build/server/chunks/3-zNUOnAaM.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/configuration.yaml'
}
Error reading or parsing ./data/dashboard.yaml: Error: ENOENT: no such file or directory, open './data/dashboard.yaml'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async loadFile (file:///rootfs/build/server/chunks/3-zNUOnAaM.js:8:18)
    at async Promise.all (index 1)
    at async load (file:///rootfs/build/server/chunks/3-zNUOnAaM.js:16:38)
    at async load_server_data (file:///rootfs/build/server/index.js:1891:18)
    at async file:///rootfs/build/server/index.js:3301:18 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './data/dashboard.yaml'
}

**Comment by matt8707** [comment]
Error: ENOENT has been fixed, please rebuild to pull the latest changes

![screen](https://github.com/matt8707/ha-fusion/assets/36163594/4746fe66-f373-4c54-9023-7a5a2e1b1c2d)

**Comment by briiiian** [comment]
![image](https://github.com/matt8707/ha-fusion/assets/149789819/2cc7d9fd-0ec6-459b-ac14-b162d7915ab0)
I just upgrade latest version, and rebuild it. but also shows those logs
![image](https://github.com/matt8707/ha-fusion/assets/149789819/c378c873-077c-4bb1-b969-38fe30c19d01)

**Comment by Holewijn** [comment]
2023.12.4 fixed the most but im getting this 
![image](https://github.com/matt8707/ha-fusion/assets/16470505/1af96ab6-1793-4ea7-8ee1-49d09170a594)

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2023.12.5

@Holewijn what do you mean? configuration.yaml is created once you save the settings for the first time

**Comment by briiiian** [comment]
it looks well in 2023.12.15. thx
