### ISSUE TITLE
Camera real time view in object

### ISSUE THREAD

**Issue by denveronly** [matt8707/ha-fusion#111]
Howdy!
Work is going great i see from last i visited.

I wonder if it is possible to make an option to show a camera with a ongoing stream (now it is still picture and if clicked it shows pop up window with stream)

im really looking to make the dashboard on a tablet and that is crucial for me as im streaming my doorbell

**Comment by matt8707** [comment]
It should be a stream...

**Comment by denveronly** [comment]
Stream is only on sidebar. On mainbar have a still image

**Comment by mape** [comment]
Wonder if this is related to https://github.com/matt8707/ha-fusion/issues/61#issuecomment-1879995696, max concurrent connections per domain limiting the iframe from loading.

@denveronly Do you have multiple cameras on the dashboard?

**Comment by denveronly** [comment]
Yea, was using 2 cameras

**Comment by moharith** [comment]
I also don't have a stream from my nest cam indoor
