### ISSUE TITLE
Clock showing 24 instead 00

### ISSUE THREAD

**Issue by mkredoine** [matt8707/ha-fusion#114]
Hi. The clock shows 24:16 instead of 00:16. Is it a bug ?
Thx

**Comment by matt8707** [comment]
Could it be related to https://github.com/matt8707/ha-fusion/issues/104?

**Comment by matt8707** [comment]
Did [2024.1.3](https://github.com/matt8707/ha-fusion/releases/tag/2024.1.3) fix this?

**Comment by mkredoine** [comment]
No. Still showing 24 at midnight even with 2014.1.3.

**Comment by domored** [comment]
hello, 2024.1.4 fixed the problem. thx and great job.
