### ISSUE TITLE
when selecting a person the Map is not showing up

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#121]
when selecting a person the Map is not showing up
![image](https://github.com/matt8707/ha-fusion/assets/23150947/756c058e-f8f2-4237-a554-957cd04bc3a6)

**Comment by matt8707** [comment]
Yeah, you just opened another identical issue https://github.com/matt8707/ha-fusion/issues/120

https://github.com/matt8707/ha-fusion/blob/main/static/documentation/Map.md

**Comment by canedje** [comment]
Oke, but wereld find:
Settings > Addons > Maptiler
In donker Fusion?

**Comment by matt8707** [comment]
Yes, I guess I can make it more clear if api key is missing



![1](https://github.com/matt8707/ha-fusion/assets/36163594/e09f1d42-c045-4b7a-935b-b626d283001f)

![2](https://github.com/matt8707/ha-fusion/assets/36163594/1f85a7c8-81df-421d-9dd3-19fff0ce91d6)

**Comment by canedje** [comment]
Ahhhhh. Thanks again

**Comment by nagtegaal** [comment]
Why not in the Home Assistant “Confifuration” tab of the add-on? Op 7 jan 2024 om 21:28 heeft Mattias Persson ***@***.***> het volgende geschreven:﻿
Yes, I guess I can make it more clear if api key is missing
1.png (view on web)
2.png (view on web)
