### ISSUE TITLE
Respect precision of sensor status

### ISSUE THREAD

**Issue by nagtegaal** [matt8707/ha-fusion#123]
The set precision (amount of decimals) of status set in home assistant isn't respected. Would be nice to have this respected inside Fusion too.
It would be also nice, to have the ability to set it here, with backwards compatibility to HA itself. (Not sure if this is possible at all)

**Comment by matt8707** [comment]
Can you give examples of where this happens, what happens and what you expect to happen?

**Comment by nagtegaal** [comment]
<img width="1199" alt="Scherm­afbeelding 2024-01-09 om 08 29 12" src="https://github.com/matt8707/ha-fusion/assets/105111224/90e9613e-3fbc-4753-86f3-ba58cfa9682a">
<img width="423" alt="Scherm­afbeelding 2024-01-09 om 08 30 53" src="https://github.com/matt8707/ha-fusion/assets/105111224/8652856f-cba5-44e0-a6c9-7de5716da1e2">

Precision, the amount of numbers behind the comma, or dot in bigger numbers. See attached screenshots of the exact same sensor.

The same applies to unit_of_measurement, which isn't changeable inside ha-fusion. But perhaps that is a feature request...

**Comment by matt8707** [comment]
Just had a look. [display_precision](https://www.home-assistant.io/blog/2023/03/01/release-20233/#sensor-display-precision) in .storage/core.entity_registry isn't accessible from the API as far as I can tell. 

Maybe an option to round the state if a number is detected?

**Comment by nagtegaal** [comment]
> Maybe an option to round the state if a number is detected?

If one couldn't get the standard Home Assistant features, perhaps an advanced "Code editor" could be implemented where people could fiddle with the code and set things manually of the desired specific sensor?
