### ISSUE TITLE
FR: Cover card

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#13]
Would be great to have basic cover controls - up/down/stop.

Thanks!

**Comment by fabianluque** [comment]
@matt8707 I’ll start working on this.

**Comment by fabianluque** [comment]
@matt8707 Created PR for this, let me know what you think. Translation is pending, couldn't find suitable strings to use.

**Comment by matt8707** [comment]
added in 2024.1.0

**Comment by Plawasan** [comment]
Great, thanks guys! Only one comment and this is very much a matter of preference but   it would seem logical to me to have the up button on the right, as that's where the position slider also goes when the cover is open/ing..
