### ISSUE TITLE
HASS (Supervised/OS version) fails to update to version 2024.1.3 due to not finding linux compatible image

### ISSUE THREAD

**Issue by xin-xw** [matt8707/ha-fusion#143]
Can't install matt8707/addon-ha-fusion-aarch64:2024.1.3: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2024.1.3&fromImage=matt8707%2Faddon-ha-fusion-aarch64&platform=linux%2Farm64: Not Found ("manifest for matt8707/addon-ha-fusion-aarch64:2024.1.3 not found: manifest unknown: manifest unknown")

**Comment by matt8707** [comment]
It's not built yet

https://github.com/matt8707/addon-ha-fusion/actions/runs/7479828170
