### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by vgnnair** [matt8707/ha-fusion#144]
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries. Trying to install in rpi3b+

**Comment by matt8707** [comment]
do you have a 32-bit os? I have a rpi3b+ and installed arm64 just fine with haos

**Comment by vgnnair** [comment]
thanks @matt8707  mine is armv71 32 bit. probably thats why

**Comment by stefan-fle** [comment]
Are there plans to automatically build for 32bit OS as well?

**Comment by matt8707** [comment]
[2024.1.5](https://github.com/matt8707/ha-fusion/releases/tag/2024.1.5)
