### ISSUE TITLE
FR: Possible to add this phu icon set

### ISSUE THREAD

**Issue by schmierlappe** [matt8707/ha-fusion#145]
https://github.com/elax46/custom-brand-icons

**Comment by matt8707** [comment]
I've looked into it. The file is very large, and I would need to write custom code to parse just this set. Therefore, it's better if you ask elax46/custom-brand-icons to publish the icon set on Iconify https://iconify.design/docs/articles/add-icon-set/

**Comment by elax46** [comment]
> I've looked into it. The file is very large, and I would need to write custom code to parse just this set. Therefore, it's better if you ask elax46/custom-brand-icons to publish the icon set on Iconify https://iconify.design/docs/articles/add-icon-set/

Thanks for your suggestion, I just sent the request

**Comment by elax46** [comment]
hi I wanted to inform you that the whole set of icons is also available in the Iconify framework, feel free to use them

**Comment by matt8707** [comment]
awesome!
