### ISSUE TITLE
FR: Add possibility of using an entity state as image URL

### ISSUE THREAD

**Issue by anarion80** [matt8707/ha-fusion#154]
Please consider an option to use an entity state as option for image URL to allow for dynamic changes.

Or perhaps directly full HA (Jinja) template evaluation using other entities' states and attributes ;)

**Comment by matt8707** [comment]
for the sidebar image type, right?

**Comment by matt8707** [comment]
I'm closing this

Template for image domain already exist
https://www.home-assistant.io/integrations/template/#image

and in ha-fusion you can use sidebar 'template' to do this as well

```jinja2
{% if 1 + 1 == 2 %}
  <img src="http://placekitten.com/200/300" style="width: 100%;">
{% else %}
  <img src="https://placekitten.com/200/140" style="width: 100%;">
{% endif %}
```

**Comment by anarion80** [comment]
Thanks, didn't know about the image template!
