### ISSUE TITLE
Bug: Camera not filling card

### ISSUE THREAD

**Issue by jaburges** [matt8707/ha-fusion#158]
<img width="387" alt="image" src="https://github.com/matt8707/ha-fusion/assets/14154875/84cfbc78-9aef-462e-80df-18685d00d480">

Top and bottom corners the same

**Comment by Breakingx** [comment]
+1
Occurs to me in the IOS  Home Assistant companion App, too.

**Comment by fabianluque** [comment]
Yes, this happens to me too with my Nest doorbell. All other cameras look fine.
