### ISSUE TITLE
Addon won't start?

### ISSUE THREAD

**Issue by Bandy325** [matt8707/ha-fusion#16]
Today I installed this big promising addon (2023.12.7) and then cleaned the cache(several times) and restarted Home Assistant. When I start the addon it keeps starting for a while and then stops. The log of the addon fetches the following information:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
listening on port 5050
env HASS_URL undefined
env ADDON true

The only thing HA's "log viewer" addon shows is the following TypeError: argument of type 'int' is not iterable.

Edit:

I have now installed the addon and reinstalled it twice. When I start the add-on, after a while I get the message "check supervisor log". Here is my supervisor log...

TypeError: Illegal constructor
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566)
E (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
/hacsfiles/lovelace-card-mod/card-mod.js:1:39893
2023-12-28 11:37:00.245 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store/repositories - Can't add https://github.com/matt8707/addon-ha-fusion, already in the store
2023-12-28 11:37:02.788 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store/repositories - Can't add https://github.com/matt8707/addon-ha-fusion, already in the store
2023-12-28 11:37:20.199 ERROR (MainThread) [frontend.js.latest.202312270] Uncaught error from Chrome 120.0.0.0 on Windows 10
TypeError: Illegal constructor
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566)
E (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
/hacsfiles/lovelace-card-mod/card-mod.js:1:39893
2023-12-28 11:40:43.464 ERROR (MainThread) [frontend.js.latest.202312270] Uncaught error from Chrome 120.0.0.0 on Windows 10
TypeError: Illegal constructor
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566)
E (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
/hacsfiles/lovelace-card-mod/card-mod.js:1:39893
2023-12-28 11:40:48.423 ERROR (MainThread) [frontend.js.latest.202312270] Uncaught error from Chrome 120.0.0.0 on Windows 10
TypeError: Illegal constructor
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:10144)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new r (/hacsfiles/lovelace-card-mod/card-mod.js:1:15236)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new n (/hacsfiles/lovelace-card-mod/card-mod.js:1:32733)
o.<anonymous> (/hacsfiles/lovelace-card-mod/card-mod.js:1:9380)
new o (/hacsfiles/lovelace-card-mod/card-mod.js:1:45566)
E (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
/hacsfiles/lovelace-card-mod/card-mod.js:1:39893
2023-12-28 11:40:48.424 ERROR (MainThread) [frontend.js.latest.202312270] Uncaught error from Chrome 120.0.0.0 on Windows 10

So something seems to be going wrong with "card-mod". Unfortunately I don't have enough knowledge to solve this myself.

**Comment by Albometer** [comment]
Same Issue here ... it works and after a while it stopped with the same Error.

**Comment by Bandy325** [comment]
Ok "suddenly" the addon works. I did 2 things... watchman complained about 2 entities, I fixed them and I happened to implement a supervisor update that just came up. I don't know if these actions actually had an impact, but I am very happy that the addon now works!

**Comment by matt8707** [comment]
I'm closing this since I don't see any issues related to ha-fusion. Please open a new one if you have any issues
