### ISSUE TITLE
Keep getting a 404 on dev install

### ISSUE THREAD

**Issue by nagtegaal** [matt8707/ha-fusion#163]
I followed The "Develop" part. here: https://github.com/matt8707/ha-fusion
But I keep getting a 404 once browser opens up a new screen.
The initial background is displayed for a short while, but after that I keep getting the same error every time in Safari/FF/Chrome on macOS Sonoma 14.2.1:

<img width="764" alt="Scherm­afbeelding 2024-01-13 om 13 20 15" src="https://github.com/matt8707/ha-fusion/assets/105111224/783ab4f6-5360-496b-90bb-310a73fceb6b">

Could someone tell me how this could be fixed?

**Comment by matt8707** [comment]
Please use discussions instead https://github.com/matt8707/ha-fusion/discussions
You need to edit `.env` file
