### ISSUE TITLE
Buttons disabled

### ISSUE THREAD

**Issue by cmacrowther** [matt8707/ha-fusion#17]
Wanted to firstly thank you for the great work on this dashboard. It looks great!

I have pulled down the latest image, but the "Buttons" button is greyed-out and disabled.  Was this an error in configuration or was there something I missed?
![image](https://github.com/matt8707/ha-fusion/assets/12267484/bc18b30d-25c7-46cf-987d-44e41833f8bf)

**Comment by Holewijn** [comment]
Try make a section first and then u can drag the button to the horizontal stack

**Comment by cmacrowther** [comment]
> Try make a section first and then u can drag the button to the horizontal stack

Ah this was the issue, looks a bug where you can't add buttons to an already created or empty section. I see @matt8707 has a bug fix in. Thanks you guys!
