### ISSUE TITLE
Can't add buttons to horizontal Stacks

### ISSUE THREAD

**Issue by AlxSZP** [matt8707/ha-fusion#176]
This broke with the latest version, I can only add buttons as sections; however, I can't add or drag or drop them in the UI inside a horizontal stack.

Current version: 2024.1.4

Note. At some point the UI gets on a bad state, when trying to edit the UI I can see the settings pop up showing another pop up UI before loading the right one.

I also tried to delete it all and restart, that was even worse... got into a bad state, somehow restarting HA got me back to the previous way it looked (last time I saved before deleting it all)

**Comment by matt8707** [comment]
> This broke with the latest version, I can only add buttons as sections; however, I can't add or drag or drop them in the UI inside a horizontal stack.

You can't add buttons to horizontal stacks, only sections can be added.

> Note. At some point the UI gets on a bad state, when trying to edit the UI I can see the settings pop up showing another pop up UI before loading the right one.

If it happens again please share your dashboard.yaml (code popup)
