### ISSUE TITLE
FR: Domain 'group' not implemented

### ISSUE THREAD

**Issue by Xitro01** [matt8707/ha-fusion#179]
Would be great to have a group pop-up as well.
Giving me some basic information about the states of each group member would already be awesome.

For example: I got a group called 'guests' which has some persons in it, which I would like to see if they're home or not.

**Comment by matt8707** [comment]
This? https://www.home-assistant.io/integrations/group/#old-style-groups

**Comment by Xitro01** [comment]
> This? https://www.home-assistant.io/integrations/group/#old-style-groups

That is indeed how I have it set-up right now.
