### ISSUE TITLE
Odroid xu4 not supported 

### ISSUE THREAD

**Issue by bencsyp** [matt8707/ha-fusion#181]
This add-on is not compatible with your machine's processor architecture or installed operating system.

Let's do it please, I really like it.
Odroid xu4, HassOS

**Comment by matt8707** [comment]
What't the architecture? armv7?

**Comment by bencsyp** [comment]
Yes

**Comment by matt8707** [comment]
[2024.1.5](https://github.com/matt8707/ha-fusion/releases/tag/2024.1.5)

**Comment by bencsyp** [comment]
Thanx
