### ISSUE TITLE
[QUESTION/Little Request] Upcoming Features and roadmap

### ISSUE THREAD

**Issue by PalmTamino** [matt8707/ha-fusion#183]
Hey, I would love to see a list of which features are currently worked on, which have been done recently, and which ones are planned.

Here an example of a github project using it, and how i imagine it looking like 
![IMG_2075](https://github.com/matt8707/ha-fusion/assets/36358673/2b338e05-f5f7-4779-949b-90ccc59053b6)

**Comment by anarion80** [comment]
Here's the progress status for this project: https://github.com/matt8707/ha-fusion/blob/main/PROGRESS.md

**Comment by PalmTamino** [comment]
> Here's the progress status for this project: https://github.com/matt8707/ha-fusion/blob/main/PROGRESS.md

Oh nice, i’m gonna close this then. Maybe consider adding this to the reader :)
