### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by WinstonGFX** [matt8707/ha-fusion#185]
Could include this Docker Compose formatted installation code in addition to Docker Run in documentation.

``
version: '3'

services:
  ha-fusion:
    image: ghcr.io/matt8707/ha-fusion
    container_name: ha-fusion
    network_mode: bridge
    ports:
      - "5050:5050"
    volumes:
      - /path/to/ha-fusion:/app/data
    environment:
      - TZ=Europe/Stockholm
      - HASS_URL=http://192.168.1.241:8123
    restart: always
``

```

**Comment by matt8707** [comment]
There already is?


### Docker

If you're using the "Container" or "Core" installation methods, ha-fusion can be installed via Docker:

1. **Docker Compose File**: Place your edited copy of the [docker-compose.yml](https://github.com/matt8707/ha-fusion/blob/main/docker-compose.yml) file in a suitable directory.

2. **Create Container**:
   Run the following commands in your terminal to start the container:

   ```bash
   cd path/to/docker-compose.yml
   docker-compose up -d ha-fusion
   ```

**Comment by WinstonGFX** [comment]
Ah, my mistake. Completely missed that. Docker Run code is inline, whereas
the Docker Compose was a text hyperlink to a file. Thought it might make
sense for Docker Compose code inline as well.

**Comment by matt8707** [comment]
docker run is a command, docker-compose is not, there could be confusion if I mix
