### ISSUE TITLE
Bug: Light group lists all supported_color_modes

### ISSUE THREAD

**Issue by matt8707** [matt8707/ha-fusion#189]
Looks like the group header is picking up multiple "Color" options from the members:

![image](https://github.com/matt8707/ha-fusion/assets/73796046/f485e92b-2b19-45b9-b508-ec320baf0476)

_Originally posted by @Plawasan in https://github.com/matt8707/ha-fusion/issues/177#issuecomment-1894399323_

**Comment by matt8707** [comment]
Hmm, you're right, but I'm not sure how to solve this. It does, however, correctly list the available color modes.

```yaml
supported_color_modes: color_temp, hs, rgbw, rgbww, white, xy
```

**Comment by Plawasan** [comment]
I would expect the group view to show the lowest common denominator of the group, i.e. only the features, that every member of the group supports... in my case it would only be a on/off toggle, if every member supported brightness then show also that bar etc etc..

**Comment by matt8707** [comment]
Right, that makes sense. You can't change the color for every light in a group if half of the group doesn't even support color. I just checked what HA does, they do the opposite, they use the greatest common denominator.



![img](https://github.com/matt8707/ha-fusion/assets/36163594/e8eb6771-5b3e-41c6-b1c0-4c80dbde2a76)

 demo rgbww light, group gets full color functionality of rgbww, hue temperature light in the mix, hue color lights

```yaml
supported_color_modes: color_temp, hs, rgbw, rgbww, white, xy
```

**Comment by anarion80** [comment]
The same happens for individual lights as well:
![obraz](https://github.com/matt8707/ha-fusion/assets/2185791/17ea1b39-0f61-4539-96c7-3557510c5ff0)

(with the particular light reporting: `supported_color_modes: color_temp, hs, rgb`)

And then we loop all color modes:
```javacript
{#each supportedColorModes as mode}
```
which creates duplicate buttons.

If feels like we should somehow map all the possible values for color_modes into one color boolean and only show one (assuming the handling is the same).

**Comment by Plawasan** [comment]
Interesting.. (obviously) same for me however it doesn't really make a lot of sense to me when you e.g. increase the brightness of the group from say 50% to 60%, all the on/off lights just come on at 100% (nothing else they can do). I understand wanting to make the behavior consistent with HA but that doesn't mean the HA implementation makes a ton of sense :)

**Comment by matt8707** [comment]
> If feels like we should somehow map all the possible values for color_modes into one color boolean and only show

Yeah, will fix that

>  I understand wanting to make the behavior consistent with HA but that doesn't mean the HA implementation makes a ton of sense

I'm just trying to understand why they chose that approach. It's more complicated to check all the children of a group to see what they support and then compare them to each other, rather than simply checking the group's "supported_color_modes." Perhaps that's the reason; it's just simpler.
