### ISSUE TITLE
Sidebar - Weather: Extra sensor shows up as humidity, "Weather" sensor value not displayed

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#191]
2024.1.5

![image](https://github.com/matt8707/ha-fusion/assets/73796046/d690212f-d26d-499c-9e78-c5d87bbdc295)

```
  - type: weather
    id: 3101484535118
    entity_id: weather.forecast_stodulky_hourly
    extra_sensor: sensor.ecowitt_wind_speed
    weather_sensor: sensor.ecowitt_yearly_rain_rate
```
![image](https://github.com/matt8707/ha-fusion/assets/73796046/e4c86cc4-6465-4191-b326-887a5a665628)

![image](https://github.com/matt8707/ha-fusion/assets/73796046/7b272f68-cdc7-407f-be89-b432908f6a7c)

Also I'm not quite sure what the difference/purpose is of entity/weather in the config? Nothing I add to "Weather" actually shows up in the sidebar?

The preview shows the extra value but the card itself does not (see above).

![image](https://github.com/matt8707/ha-fusion/assets/73796046/843aa453-eb43-42eb-96b7-1d3bcc763232)

**Comment by matt8707** [comment]
Note to self: The weather sensor should overwrite the state of the weather entity, but currently only the preview works. Extra sensor for e.g. precipitation works, but not the icon.
