### ISSUE TITLE
Please add button card 

### ISSUE THREAD

**Issue by bencsyp** [matt8707/ha-fusion#197]
Hy. Pls added button card and wake on lan option. 
![IMG_1719](https://github.com/matt8707/ha-fusion/assets/62811607/372f5d72-0ee9-44e7-8010-d5a12498ac72)

**Comment by matt8707** [comment]
I'm not sure I follow, what is this? Is `wake_on_lan` a domain? I see `wake_on_lan.send_magic_packet`, but that's a service.

https://www.home-assistant.io/integrations/wake_on_lan/#switch
WOL switch is already supported
