### ISSUE TITLE
Stackable sections

### ISSUE THREAD

**Issue by R3nierjvr** [matt8707/ha-fusion#198]
Hi

Will it be possible to add a drag and drop option to be able to stack section, or create layout options to divide horizontal stacks into different sections : for example "1 left  / 2 right" or " 1 top/ 3 below. all contained in 1 horizontal stack. I added the plex recently added section and wanted to put a sonarr & radarr recent request next to it, one below the other.

Regards.
and thx upfront

**Comment by matt8707** [comment]
No, this is not planned. It adds complexity and goes against the goal of creating an "easy-to-use dashboard." If we agree to everything, we'll just end up with another version of Lovelace.

**Comment by R3nierjvr** [comment]
Cool thx for the feedback, love the dashboard already  :)
