### ISSUE TITLE
FR: Any way to add a camera feed in the main section?

### ISSUE THREAD

**Issue by daveonkels** [matt8707/ha-fusion#2]
Just spun up the docker and it looks marvelous. I think I've figured out everything but how to create a video feed in the main section. I see you have a way to do it on the sidebar but that's a bit small for our use case.

**Comment by MiranoVerhoef** [comment]
@daveonkels on a side note, what repository did you use for the docker?

**Comment by daveonkels** [comment]
Not a repo - it's a docker build script - see these instructions:
https://github.com/matt8707/ha-fusion/blob/main/docker-compose.yml

**Comment by sincrack** [comment]
same question

**Comment by Plawasan** [comment]
Honestly it would be great to be able to use any of the cards now available in the sidebar..

**Comment by megane999** [comment]
will be cool if add integration of https://github.com/AlexxIT/go2rtc

**Comment by WeterPeter** [comment]
> Honestly it would be great to be able to use any/all of the cards now available in the sidebar..

Yeah, enhancement please! :-)

**Comment by denveronly** [comment]
Same issue
Need all that entities in main section and it would rock!
Great work btw!!

**Comment by matt8707** [comment]
im working on cameras on main dashboard
unified sidebar and main types are far off, need to get each working first

**Comment by matt8707** [comment]
added in https://github.com/matt8707/ha-fusion/releases/tag/2023.12.7
