### ISSUE TITLE
FR: Media Control Card Type

### ISSUE THREAD

**Issue by eldridgea** [matt8707/ha-fusion#20]
Love this dashboard!

I see in the readme there's a media control card, but I haven't been able to successfully get one on my instance. 

I used this form:
```
type: media
entity: media_player.chromecastaudio0472
```

When doing so I see a box titled Unknown 

<img width="595" alt="Screenshot 2023-12-28 at 2 19 40 PM" src="https://github.com/matt8707/ha-fusion/assets/5951110/83c62e98-3480-40ee-b310-41cd85d106ae">

Using the type `media-control` results in nothing being shown. 

I may just be doing something wrong or it may not be supported yet but wanted to report it.

Thanks again for the awesome project!

**Comment by matt8707** [comment]
it's not properly implemented yet, here's what I used
https://github.com/matt8707/ha-fusion/blob/c25dcd65ef0a4439efcc7d904e1aa1ad9ae36f54/data/dashboard.yaml#L53-L64

**Comment by eldridgea** [comment]
Awesome, thanks!

**Comment by vgnnair** [comment]
would love to have the  media_player_enable_art
