### ISSUE TITLE
FR: Auto Save Option

### ISSUE THREAD

**Issue by greghare** [matt8707/ha-fusion#200]
First of all, I have to say thanks for this great tool! Installing it was a breeze and was up and running in minutes, and it looks AWESOME.

So far in the short time I've been using it, I noticed that changes are not automatically saved. I spent a minute or two configuring the sidebar to look like the example, and then hit done and did not read the warning about unsaved changes and lost what I did. 

I understand this may be by design, but it would be cool if there was an option to have the dashboard save after changes are made.

**Comment by matt8707** [comment]
> and then hit done and did not read the warning about unsaved changes and lost what I did

I mean... yeah like all software ever. There is a save keyboard shortcut that you can use instead
