### ISSUE TITLE
FR: Adding Notification 

### ISSUE THREAD

**Issue by patricknitsch** [matt8707/ha-fusion#203]
Hi there,

great work. It looks amazing!

Can you add notifications? I would like trigger notifications in automations and show them in the dashboard. Is that possible?

Many thanks and greets

Patrick

**Comment by matt8707** [comment]
Do you mean [persistent_notification](https://www.home-assistant.io/integrations/persistent_notification/)?

**Comment by patricknitsch** [comment]
Yes :)
