### ISSUE TITLE
FR: Template in Button State

### ISSUE THREAD

**Issue by IzeQube** [matt8707/ha-fusion#209]
I think it would be great if we could use a template for the button state.

I have quite a lot of ESPHome Switches that also monitor the power usage. Currently it isn't possible to add attributes to ESPHome switches to show the power consumption, instead you have one entity for the switch and a sensor for the power consumption.

But if we can use a template to define our own state it is possible to show the state and also the power consumption (or something else) from another entity and/or attribute.

We've got this:
![image](https://github.com/matt8707/ha-fusion/assets/4445441/7d5f365d-248e-4853-b833-9de7fc56ad6d)

Mockup:
![image](https://github.com/matt8707/ha-fusion/assets/4445441/49630efb-dcb1-4b81-9358-2822192e2d21)

**Comment by nagtegaal** [comment]
TBHJ I think we need some kind of implementation of the "TAML-editor" vs the "GUI editor"..
That is the most flexible approach and people can always do more advanced stuff with the buttons/entity states/attributes or whatever...

**Comment by realroywalker** [comment]
I know it's really early days on this, but it would be super cool if there were similar functionality to the mushroom template card, where you can use templating for primary / secondary text and the icon and colouring.. that would make for something highly flexible for those that want to display custom info on the dashboard. Great work on this so far - it's really impressive! 👍
