### ISSUE TITLE
Ellipsis for long names

### ISSUE THREAD

**Issue by JorgeAnzola** [matt8707/ha-fusion#213]
Would it be possible to enable ellipsis for long names?

![image](https://github.com/matt8707/ha-fusion/assets/15676614/a1675f5c-1c6e-4218-b0dd-d771d7f7a3c5)

**Comment by matt8707** [comment]
You mean bottom-right name goes all the way to the edge?

**Comment by JorgeAnzola** [comment]
Yes, sorry, I forgot to highlighted it. 

"Cuadro de la escalera"

**Comment by JorgeAnzola** [comment]
I just noticed that the ellipsis actually is there, like in the first highlighted element. 
In the second one, the name just ends exactly in the border of the button.

<img width="1455" alt="Captura de pantalla 2024-01-22 a las 8 43 14" src="https://github.com/matt8707/ha-fusion/assets/15676614/e435f3f8-4d71-41fb-a453-0cd6bd9864ff">
