### ISSUE TITLE
FR: HVAC

### ISSUE THREAD

**Issue by Holewijn** [matt8707/ha-fusion#22]
Hi, i cant see all hvac modes on fusion, this is what i have in my other dashboard 

![image](https://github.com/matt8707/ha-fusion/assets/16470505/21a5b4bd-184e-46ff-9765-9a0af60c8015)

This is in Fusion 

![image](https://github.com/matt8707/ha-fusion/assets/16470505/3ae122ec-4512-421e-88ed-e4a6cbd1ebd9)

Also the color is not visible this needs to be orange or red? fan modes gives me blue 

![image](https://github.com/matt8707/ha-fusion/assets/16470505/e7657e32-f078-4dc6-938f-2371520420f0)

edit: it seems i don't get a preview of my image, i don't know why, i copy/paste it 
i'm missing; auto heat/cool, heat and humidifier.
Fan modes and swingmode doesn't work

**Comment by matt8707** [comment]
Can you try again with the images, you can drag them into your comment to upload them

**Comment by Holewijn** [comment]
> Can you try again with the images, you can drag them into your comment to upload them

they seem to work now ^^

**Comment by matt8707** [comment]
Ah, the modes actually gets added, but there's isn't icons for all of them, Colors are not implemented, only ability to set one color. Also clicking doesn't do anything yet, just logs what it should do to browser console
