### ISSUE TITLE
After latest update is person not showing up map anymore

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#221]
Hitting the person button no map is showing up anymore after latest update 2024.1.6
![image](https://github.com/matt8707/ha-fusion/assets/23150947/a5ed273d-08c8-41da-bcf8-d8bc39de600e)
Also not selecting device trackers as second attribute
EDIT: only working as device_tracker as entity
EDIT2: I do see in the notes that is the situation now. For me thats a downgrade and hoping it is coming back again in the next update

**Comment by abeksis** [comment]
As noted by matt8707. You need to generate the following data under the customize.yaml file:

`device_tracker.mobile_avi:
  friendly_name: Mobile Avi
  entity_picture: /local/avi.png`
Then use device_tracker.mobile_avi in ​​UI view

**Comment by canedje** [comment]
Thanks for the answer

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/pull/205

**Comment by canedje** [comment]
This is a good alternative!

**Comment by vgnnair** [comment]
Hi @matt8707  how do we handle if multiple device trackers decide a persons location, now that in 2024.1.6 onwards person is only sensor like( no map) and device tracker is required for maps. Can device tracker add a secondary device tracker? may a feature request?

Hi @abeksis  is customize.yaml a file that should reside within ha fusion volume ?( docker implementation)

**Comment by vgnnair** [comment]
Would also nice to get  last_updated and last_changed for device tracker in fusion which shows in HA
<img width="717" alt="image" src="https://github.com/matt8707/ha-fusion/assets/102384794/4b532d97-1164-402d-8ac6-ad7183f15d4e">
