### ISSUE TITLE
Make it default dashboard

### ISSUE THREAD

**Issue by Beelzebub2** [matt8707/ha-fusion#228]
This project is amazing!, i don't know if it was asked already but would it be possible to add the feature to turn this into the default dashboard when the home-assistant is opened?.

**Comment by thavini** [comment]
You can just expose the port in the latest version. Change the loadbalacer to route to there or just enter via IP:PORT in the browser.

**Comment by Beelzebub2** [comment]
how can i change the loadbalacer? where can i do that? im new to home-assistant

**Comment by thavini** [comment]
From your question i assume you don't have an loadbalancer to access home assistant. I think you already access it via the IP:PORT of you HA instance? Then you can just enable the the port thing in the add-on config tab choose a 4 digit number or go for the default 8099 i think.

After this your add-on will be available over that port via your brwoser. You need to access with your HA credentials.

**Comment by Beelzebub2** [comment]
ohh ok thank you!

**Comment by abeksis** [comment]
If you use the supervisor, there is an option to go to Add-ons and there under fusion you will access the settings and there under Network you will determine which port you want. Then you will have a unique address (HA's IP address) plus the port you added.
