### ISSUE TITLE
FR: Car view in sidebar

### ISSUE THREAD

**Issue by MrOlof** [matt8707/ha-fusion#23]
Would be nice to have a car card like this in the sidebar:
![image](https://github.com/matt8707/ha-fusion/assets/100124559/bba14f56-e5fd-424c-9399-cfa940ee4753)

Credit: https://github.com/VigoKrumins/hass-config/

**Comment by matt8707** [comment]
This doesn't exist in home assistant right? It would have to be a completely custom implementation, and therefore I will not focus on this anytime soon.

**Comment by maddox** [comment]
Having a flexible Picture Elements type card could possibly allow us create something like this and would be more valuable to the project in general.

**Comment by matt8707** [comment]
Yeah, closing in favour of https://github.com/matt8707/ha-fusion/issues/49
