### ISSUE TITLE
Fusion crashes within Home Assistant app on iPad

### ISSUE THREAD

**Issue by matejgordon** [matt8707/ha-fusion#230]
Hello,

I'm encountering an issue where the Fusion is crashing when accessed through the Home Assistant app on my iPad Air (4th generation) with iPadOS 17.2. The site opens briefly before crashing. Here are the details:

Device: iPad Air (4th Generation)
Operating System: iPadOS 17.2

Steps to Reproduce:
    Open the Home Assistant app on the iPad.
    Try to access the Fusion app from within Home Assistant.
    
https://github.com/matt8707/ha-fusion/assets/16642830/64617708-a81d-4f9c-8fee-6dddf45c7ca9

**Comment by larsoss** [comment]
Refresh catch?

**Comment by matt8707** [comment]
Yeah, please try Settings > Companion App > Debugging > Reset Frontend Cache

**Comment by matejgordon** [comment]
That fixed the issue, thanks :)
