### ISSUE TITLE
FR: custom text for attributes

### ISSUE THREAD

**Issue by t0bse** [matt8707/ha-fusion#235]
I would love to have a text to my attributes, like "current temp:" or only "°C" behind the current temperature (19.4 in "Büro"), like a suffix/prefix in the sensor template.

![image](https://github.com/matt8707/ha-fusion/assets/45834518/fdf6161e-62dd-408a-8f5b-9849c4a4d535)

**Comment by canedje** [comment]
"°C" good enough for me

**Comment by t0bse** [comment]
> "°C" good enough for me

doesn't work if you choose other attributes, like a battery level, custom text would be the best solution in my opinion. 
with custom text you could also use abbreviations to make it fit the screen

**Comment by matt8707** [comment]
duplicate of https://github.com/matt8707/ha-fusion/issues/209
