### ISSUE TITLE
Purpose of youtube sensor in the settings

### ISSUE THREAD

**Issue by johntdyer** [matt8707/ha-fusion#239]
Hello,

   I cant find any info on this in the docs and I am curious what the youtube sensor field is for in the settings of ha-fusion?  Thanks, and appreciate all the awesome work and crazy velocity this seems to be making !! 

Regards,

John

**Comment by johntdyer** [comment]
Yea, thats kinda what I thought too... but when I use it and put the sensor.youtube_watching into this field nothing seems to happen.... which is why I opened the ticket :)

**Comment by matt8707** [comment]
Thanks, yeah it did nothing, I've removed it now

**Comment by willsanderson** [comment]
Any plans to incorporate the sensor.youtube_watching into the Media card as a conditional similar to your previous dashboard?
