### ISSUE TITLE
FR: Vacuum Card

### ISSUE THREAD

**Issue by xADDRx** [matt8707/ha-fusion#24]
Hi,

Is it possible to design a card for the vacuum robots or perhaps via a popup?

at the moment:

![grafik](https://github.com/matt8707/ha-fusion/assets/64784940/596667d7-bb90-4c9f-bf2c-db88e163a3ad)

![grafik](https://github.com/matt8707/ha-fusion/assets/64784940/9e180531-160c-4d05-8d72-22a9a3006144)

Thank you

**Comment by MrOlof** [comment]
He did this in his previous design with a pop up, might be coming:
![image](https://github.com/matt8707/ha-fusion/assets/100124559/7ac2b731-0cf9-4a3e-affa-399bfc136e6c)
