### ISSUE TITLE
Bug: 2024.1.7 auth flow doesn't work when MFA is enabled

### ISSUE THREAD

**Issue by taylorfinnell** [matt8707/ha-fusion#246]
Disabling MFA allows authentication to function

**Comment by Xitro01** [comment]
Yep, the update broke the add-on for me. Worked before while having MFA active.

**Comment by stiltjack** [comment]
Yup. Same here. Disabling MFA is not an option.

**Comment by larsoss** [comment]
What is MFA? My fusion now shows my setup only everything is unavailable

**Comment by Andreasjkoch** [comment]
> What is MFA? My fusion now shows my setup only everything is unavailable

Multi-factor authentication. The 6 "pin" digit that generates every 30 seconds (if enabled)

**Comment by larsoss** [comment]
> > What is MFA? My fusion now shows my setup only everything is unavailable
> 
> Multi-factor authentication. The 6 digit "pin" that regenerates every 30 seconds (if enabled)

That is off for me.

**Comment by Andreasjkoch** [comment]
> > > What is MFA? My fusion now shows my setup only everything is unavailable
> > 
> > 
> > Multi-factor authentication. The 6 digit "pin" that regenerates every 30 seconds (if enabled)
> 
> That is off for me.

Yeah I think generally this login prompt doesn't work very well. I created a test user without MFA and this user isn't able to login either with no error message whatsoever

**Comment by larsoss** [comment]
Indeed. I try to login and have only a spinning wheel.

**Comment by Andreasjkoch** [comment]
I don't even have a spinning wheel lol

**Comment by emily-pesce** [comment]
I'm seeing this error: 

`Failed to load
http://homeassistant.local:8123/api/hassio_ingress/L1f6sqmPu40HmdeletedGwAKVwAr8/api/auth
resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by Daneish** [comment]
Better to create a dedicated user for Fusion with only local and non-admin access, instead of disabling MFA on your main account.

**Comment by notorioustubze** [comment]
Works fine for me on local network but when trying to access remotely I just get the spinning wheel after entering credentials.

**Comment by funka84** [comment]
Had the same issue, i changed  under option the url from "homeassistant.local:8123" to "http://homeassistant.local:8123" and then i was able to log in. Maybe it will help someboday

**Comment by Gwenlad** [comment]
nothing work for me :( maybe because I'm on Unraid ?
