### ISSUE TITLE
A problem with the meteocons icon set display under the weather

### ISSUE THREAD

**Issue by abeksis** [matt8707/ha-fusion#248]
Thanks for the latest update.

In internal access under port 8123 there is a problem with the icons of the meteocons set.
Under Custom port the icon set is displayed.

![image](https://github.com/matt8707/ha-fusion/assets/10877299/b874e396-297a-407f-b181-733258a74044)

**Comment by larsoss** [comment]
Did you refresh you're catch

**Comment by abeksis** [comment]
Of course, and I even switched to incognito mode and the same thing there.

**Comment by matt8707** [comment]
This is a bug with all images in addon

**Comment by EvanBarbour3** [comment]
@abeksis  I've managed to replicate this and have raised a PR here: https://github.com/matt8707/ha-fusion/pull/268
