### ISSUE TITLE
2024.1.7 Prevented Fusion from Starting

### ISSUE THREAD

**Issue by 550grand** [matt8707/ha-fusion#250]
Just a note, after install Fusion would no longer start. I just had to set the Home Assistant URL on Fusion's configuration page again (which was blank) and then it started working again.

Leaving this here for anyone wondering why Fusion no longer starts. The error I was receiving in the GUI when trying to start the add-on was basically "Failed to start", so was not very helpful.

Note: When upgrading, I clicked the install button to install the update, and then almost immediately I received the message that there were no updates to install, but found that indeed the update did take place. So, maybe this was just an oddity with my specific HA instance having a hiccup which caused this consequence.

**Comment by emily-pesce** [comment]
Same happened to me and I did the same re-configuration But, now I am stuck at a dialog that asks for my login to give Fusion access to the instance. Entering the info and pressing the Log In button does nothing.

<img width="542" alt="image" src="https://github.com/matt8707/ha-fusion/assets/2148735/041b6f56-20d4-47a8-88e7-09ae974f683b">

**Comment by emily-pesce** [comment]
Might be same as here: 

_Originally posted by @emily-pesce in https://github.com/matt8707/ha-fusion/issues/246#issuecomment-1905150046_

**Comment by leonkdk** [comment]
<img width="515" alt="Skærmbillede 2024-01-23 kl  06 31 35" src="https://github.com/matt8707/ha-fusion/assets/34554431/3f20001f-da85-4f02-aa96-31113f4b5a3c">

I am seeing the same exact error as @emily-pesce on this one! ;-)

**Comment by Mareckil** [comment]
Had the same issue. Needed to type http://ha-sddress:8... In configof fusion

**Comment by leonkdk** [comment]
> <img alt="Skærmbillede 2024-01-23 kl 06 31 35" width="515" src="https://private-user-images.githubusercontent.com/34554431/298815237-3f20001f-da85-4f02-aa96-31113f4b5a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODgzMTgsIm5iZiI6MTcwNTk4ODAxOCwicGF0aCI6Ii8zNDU1NDQzMS8yOTg4MTUyMzctM2YyMDAwMWYtZGE4NS00ZjAyLWFhOTYtMzExMTNmNGI1YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA1MzMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWUxOGNkMGQ4Yjg4ZTkwZGNhNDk2NGFmOTdlNjVjOGZiY2M5MTNjOWI5ZjlmYTc1OGZjNjc1ZTdlYmQ3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGIS9Q1sZ4evwS4YZrHTbkdkl9WFbQs5CdoBASt40cU">
> 
> I am seeing the same exact error as @emily-pesce on this one! ;-)

Update - I fixed it by switching OFF my 2factorAuthentification.

**Comment by meanaverage** [comment]
When you create an add-on so good that people disable 2-FA for it. Love it.

**Comment by meanaverage** [comment]
> Had the same issue. Needed to type http://ha-sddress:8... In configof fusion. There must be http:// in the address.

I can confirm this is the fix. I set this without the http:// prefix to test and cleared browser cache, and it indeed did hang. Adding http:// once again to complete the URL let me in just fine.

**Comment by patricknitsch** [comment]
Had the same issue. Setting with http:// works.

**Comment by JamesKennewell** [comment]
To add to this its cant have / at the end either.
Must be formatted like http://192.168.1.100:8123

**Comment by patricknitsch** [comment]
Is given as an example in the configuration

**Comment by nlindblo** [comment]
I'm having the same problem and have my HA environment variable set to https://<HA fqdn> which has worked until 2024.1.7. I dont see a failed login in HA either
