### ISSUE TITLE
After update 2024.1.7 update , new log-in popup does not function (login button us unresponsive) - Unable to access fusion dashboard

### ISSUE THREAD

**Issue by wilksy** [matt8707/ha-fusion#254]
After update fusion failed to start (needed HA url in config, I was not aware)

Then,when navigating to fusion dashboard, a new login(give access to HA) pop up appears. Entering a checked correct admin user name and password did not work. 

The login button was unresponsive, no message or any feedback provided by Fusion.

As is stands, I'm unable to use the dashboard.

<img width="371" alt="image" src="https://github.com/matt8707/ha-fusion/assets/27734612/d8d0ef85-adf7-4aa3-9a21-1b316a863098">

**Comment by wilksy** [comment]
log... 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
[HPM] Proxy created: /  -> http://192.168.1.157:8123/
ENV HASS_URL: http://192.168.1.157:8123/
ENV PORT: 8099
ENV ADDON true

**Comment by wilksy** [comment]
presumed issue with new authentication stuff..

 http://homeassistant.local:8123/api/hassio_ingress/..../api/auth 500 (Internal Server Error)

**Comment by intINk** [comment]
Same here, cannot use the dashboard.
I did however manage to get a loading splash after pressing log in one time:
![image](https://github.com/matt8707/ha-fusion/assets/3065261/0caf170d-68ab-4f92-b623-b8d8b4243351)

seemed to do nothing though - kept loading for hours and a refresh later i was back to square one with the login and unresponsive button

**Comment by Jordenjj** [comment]
Yep, this update broke it. Anyone tried a rollback? Really don't want to use my config :')

**Comment by wilksy** [comment]
changing HA url to http://homeassistant.local:8123/ rather the the ip address fixed it for me.

Obviously a bit of work to do anyway and it still fails for some with MFA on.

<img width="538" alt="image" src="https://github.com/matt8707/ha-fusion/assets/27734612/9fca55c9-c0c2-4bac-a593-3035689affd5">

**Comment by Jordenjj** [comment]
> http://homeassistant.local:8123/

This doesn't work for me.

**Comment by intINk** [comment]
> changing HA url to http://homeassistant.local:8123/ rather the the ip address fixed it for me.
> 
> Obviously a bit of work to do anyway and it still fails for some with MFA on.
> 
> <img alt="image" width="538" src="https://private-user-images.githubusercontent.com/27734612/298880369-9fca55c9-c0c2-4bac-a593-3035689affd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDIxMjIsIm5iZiI6MTcwNjAwMTgyMiwicGF0aCI6Ii8yNzczNDYxMi8yOTg4ODAzNjktOWZjYTU1YzktYzBjMi00YmFjLWE1OTMtMzAzNTY4OWFmZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjdmMjJiMmVlMWIzNWVkMDgyMDg1MjUzNTA0MTUzNzIxZjhiYjI4NTg2MmE0NzFjMjYwZTgwZTk5NTkyNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YZYf3sIw9U9jK4_3pJc02_ll1o_Wi6I-S9UgxlH1m34">

Tried that but to no avail. I do have MFA on, that might be it, ill check that when i can

**Comment by wilksy** [comment]
> > changing HA url to http://homeassistant.local:8123/ rather the the ip address fixed it for me.
> > Obviously a bit of work to do anyway and it still fails for some with MFA on.
> > <img alt="image" width="538" src="https://private-user-images.githubusercontent.com/27734612/298880369-9fca55c9-c0c2-4bac-a593-3035689affd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDIxMjIsIm5iZiI6MTcwNjAwMTgyMiwicGF0aCI6Ii8yNzczNDYxMi8yOTg4ODAzNjktOWZjYTU1YzktYzBjMi00YmFjLWE1OTMtMzAzNTY4OWFmZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjdmMjJiMmVlMWIzNWVkMDgyMDg1MjUzNTA0MTUzNzIxZjhiYjI4NTg2MmE0NzFjMjYwZTgwZTk5NTkyNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YZYf3sIw9U9jK4_3pJc02_ll1o_Wi6I-S9UgxlH1m34">
> 
> Tried that but to no avail. I do have MFA on, that might be it, ill check that when i can

Try MFA ( if you don't like it off create a temp new user with it off until it's sorted)

**Comment by Jordenjj** [comment]
Both the link, and the local hostname do not work with MFA off here. So there might be other culprits.

**Comment by wilksy** [comment]
> Yep, this update broke it. Anyone tried a rollback? Really don't want to use my config :')

yeah, this dashboard has made it for me. I'm not going back to the default, even if I have missing functionality whilst (hopefully) it's get developed. When I get time I plan on contributing.

**Comment by intINk** [comment]
> EDIT: I've found that http://homeassistant.local:8123/ doesn't work But http://homeassistant.local:8123 does. The slash at the end matters

Didnt work for me, got the loading thing again i referenced in my first comment - its stuck on the loading-gif

**Comment by Jordenjj** [comment]
> Didnt work for me, got the loading thing again i referenced in my first comment - its stuck on the loading-gif

Is this with or without MFA?

**Comment by Jordenjj** [comment]
> Use an ip address for example:

This does not seem to work at all for me. Just the hostname will work, without a trailing /.

**Comment by hiddevanbrussel** [comment]
Same issue here. Tried it on IP en Hostname, but same issue. I also use MFA. For now set it back to version 2014.1.6

**Comment by t0bse** [comment]
my home assistant ip: 192.168.1.11:8123
settings add-on: http://192.168.1.11:8123

user is a „only local“ one
settings 2fa is totp

works for me. only cloudflare proxy with my https domain is not working yet, maybe it‘s the settings

**Comment by dos1973** [comment]
I have tried all combination of ip or homeassistant.local you mentioned here. I get only a black screen.

**Comment by Donkie** [comment]
Removing the slash at the end of the URL as mentioned fixed it for me

**Comment by Erudition** [comment]
Here's the logs in the dev console
``` 
XHRPOST
http://100.64.2.103:8123/api/hassio_ingress/Kfqi7hqunXV539NqJEBB9nMJw7fX2eh26zKJbQb02SE/api/auth
[HTTP/1.1 500 Internal Server Error 37ms]

	
message	"Failed to parse URL from 100.64.2.103:8123/auth/login_flow"
```

**Comment by Erudition** [comment]
In the config I had: `100.64.2.103:8123`
And I can confirm that changing it to `http://100.64.2.103:8123` let me log in.

**Comment by henryceron** [comment]
> In the config I had: `100.64.2.103:8123` And I can confirm that changing it to `http://100.64.2.103:8123` let me log in.

I can confirm this worked for me too, but I had to log out in the fusion dashboard settings to log in again.

**Comment by Marc3l1988** [comment]
@matt8707 
> MFA is not implemented yet. I'll look into it

It seems that it has nothing to do with the 2FA. Because I can log in when I'm local on my network.
But, when I'm outside my network, I can't log in. and keep getting the turning circle over and over. 

I'm using the same user (local as outside), and I didn't change my URL in the settings of the add-on. So, I don't think this is a 2FA problem, but there is something else happening.

Also, I have always used 2FA in Home Assistant. And with the previous version of your add-on, there was no problem at all with logging in from the outside.
