### ISSUE TITLE
All entities unavailable after update

### ISSUE THREAD

**Issue by ahlstromanton** [matt8707/ha-fusion#257]
Had to update the url to my instance after the update. After doing so and logging in again, all entities are unknown. If I restart the addon, I don't get a login prompt again, but all enteties still broken.

I also noticed that if setting the url to http://homeassistant.local:8123, it changes the ip to 192.168.1.11 after starting - but my instance ip is 192.168.1.5. 

![image](https://github.com/matt8707/ha-fusion/assets/58640347/974037d5-5753-4a44-8017-ae1b5045e94c)
![image](https://github.com/matt8707/ha-fusion/assets/58640347/3b429aa2-3285-4643-ac00-23b0d89d46d3)
![image](https://github.com/matt8707/ha-fusion/assets/58640347/0a16b65b-eb55-4f00-8457-8bdc7e377e22)

**Comment by Write** [comment]
Same issue here, some websocket error in console that is instead of ws://homeassistant.local:8123/api/websocket my IP set in config

Error in console says : was not allowed to run insecure content from ws://homeassistant.local:8123/api/websocket

**Comment by canedje** [comment]
Try logout and login at settings.
That worked for me

**Comment by pservais** [comment]
Same as canedje, logout in settings, reload page and login.

**Comment by Write** [comment]
Indeed login out / login in does work.
