### ISSUE TITLE
Can't delete missing entity

### ISSUE THREAD

**Issue by Donkie** [matt8707/ha-fusion#258]
If I remove an entity in homeassistant which I have a card for in Fusion, the card displays missing as expected, but when I open it to remove the card, nothing happens and this error appears in the console.

![image](https://github.com/matt8707/ha-fusion/assets/2332094/09c2e786-ab1c-4cf3-9486-8f14435ab746)

A workaround currently is to move the card to a new section, and then delete that section.

**Comment by meanaverage** [comment]
Had this issue many times as well. Same solution used.

**Comment by pservais** [comment]
You can delete the lines of code for this card in the code editor. Thats how I did it.
