### ISSUE TITLE
Weather not displayed correct

### ISSUE THREAD

**Issue by dos1973** [matt8707/ha-fusion#259]
hi,

I Love Fusion!

i have a bug by displaying the new weatherforecast
<img width="229" alt="Bildschirmfoto 2024-01-23 um 19 19 43" src="https://github.com/matt8707/ha-fusion/assets/46686989/1d6b3de3-39d2-4661-b56e-1746832fc01b">

the values are too close to the weather symbols. No difference by changing to other weather source. 
Always like this

**Comment by matt8707** [comment]
@EvanBarbour3 would you mind taking a look?

**Comment by EvanBarbour3** [comment]
@dos1973 

Do you mind giving me some details to debug this? I can't currently replicate this, could you provide the following:

- Browser version
- OS
- The data provider / forecast plugin you're using
- Anything else you think relevant

Thanks!

**Comment by dos1973** [comment]
Hi,

Im really starter with HA, i'll tell you all you ask me, i don't have much experience what could be wrong.

Currently this happens on my macbook and ipad pro with safari
All mostly uptodate.

HA is running on Proxmox as VM

Will send you tonight more details.

**Comment by dos1973** [comment]
it looks like its some Apple Safari bug.

opening on chrome, on my macbook the weather looks good
<img width="317" alt="Bildschirmfoto 2024-01-24 um 18 18 18" src="https://github.com/matt8707/ha-fusion/assets/46686989/da4fbaec-3ff4-4a9d-982d-5c002bfa7c53">


homeassistant core: 2024.1.4
supervisor 2023.12.1
os 11.4
frontend 20240104.0

i hvae errors on all my apple devices
Macbook Pro: 
- sonoma 14.1.1 (23B81)
- safari Version 17.1 (19616.2.9.11.7)

iphone 15pro max
- ios 17.2.1

ipad pro 
- ios 17.2.1

home assistant app show the same behavior on iphone/ ipad

if you need more let me know
