### ISSUE TITLE
Section as Navigation Link

### ISSUE THREAD

**Issue by dos1973** [matt8707/ha-fusion#264]
Hi,

is it possible to make an Section Name `optional` as Navigation to another View?
maybe show an small icon if its as Link configured, aligned left or right

example: i have on my dashboard the living-room blinds, on another view all other blinds
i would like to be able to navigate without to different views without having an menu.

**Comment by matt8707** [comment]
I will not implement this, there's already views and sidebar navigation

**Comment by dos1973** [comment]
Hi, its not the answer i wish to read, but i respect these.

Was an idea/ option to save some space... when navigation becomes to big.
