### ISSUE TITLE
Published on ipad - HA sidebar

### ISSUE THREAD

**Issue by Bad3m3ist3r** [matt8707/ha-fusion#267]
when i open fusion on the ipad, i can't hide the homeassistant bar like i can with lovelance. Am I doing something wrong, have I overlooked something, or does this not yet exist?

![CleanShot 2024-01-24 at 10 28 44](https://github.com/matt8707/ha-fusion/assets/157047741/927f7480-9b49-4e09-b66f-6a3c7bd4abd1)

**Comment by abeksis** [comment]
There is another method. Access the settings under fusion and there enable as it is shown in the picture. After that, open the address including the port you specified in the settings - and everything will be in full screen.

![image](https://github.com/matt8707/ha-fusion/assets/10877299/94e614ec-d988-4070-8e0e-4cf470b40b3c)

**Comment by Bad3m3ist3r** [comment]
wow...great :)! Thanks for your fast reply 👍
