### ISSUE TITLE
Error when trying to edit view

### ISSUE THREAD

**Issue by ahlstromanton** [matt8707/ha-fusion#270]
![image](https://github.com/matt8707/ha-fusion/assets/58640347/c9e19632-f592-4eb5-9fa7-a417f4c5d5e0)

`kSIzPs7A30U10jahisp2…ontnZXtZATR5jPyU/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://<domain>/api/hassio_ingress/kSIzPs7A30U10jahisp2zJALHi7ontnZXtZATR5jPyU/_app/immutable/chunks/ViewConfig.tyLEJxZs.js`

**Comment by matt8707** [comment]
I cannot replicate this, did this happen once (network issue) or all the time?
