### ISSUE TITLE
Media Information

### ISSUE THREAD

**Issue by dos1973** [matt8707/ha-fusion#274]
Hi,

its not an issue, more a "would like to have".
i can't manage "Plex - recently add" to work in my environment.

but i like the style - is there any chance -to show there any image - aslong no media is active?
or anything other cool - currently its just blank. 

i think not all Users will have Plex running. Thanks

<img width="498" alt="Bildschirmfoto 2024-01-24 um 23 35 31" src="https://github.com/matt8707/ha-fusion/assets/46686989/5fd79071-3c4c-432a-9b1b-2b1e1c5b49da">

**Comment by matt8707** [comment]
Media support has not yet been implemented; you can open issues regarding it once it is.
