### ISSUE TITLE
After update to 2024.1.8 Cameras unavailable 

### ISSUE THREAD

**Issue by Mareckil** [matt8707/ha-fusion#275]
They work fine when fusion opened from ha, but doesnt when opened trough ip address

SvelteKitError: Not found: /api/camera_proxy_stream/camera.camera2
    at resolve2 (file:///rootfs/build/server/index.js:4027:18)
    at resolve (file:///rootfs/build/server/index.js:3859:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3857:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}

**Comment by abeksis** [comment]
This bug is known. And it was registered several times, I believe that a correction will come later.

**Comment by Mareckil** [comment]
Well. I do not know if you mean about the bug in version 6 which was fixed in version 7. But now it came back in version 8.

**Comment by Gerrett84** [comment]
Unfortunately it also works in version 2024.1.9 

'''
[HPM] Error occurred while proxying request 192.168.178.151:5050/api/camera_proxy/camera.doorbell_repeater_405c?token=d874904deddd82b67e76fcb8fa8c1494f9e44ab72e91a90999b7047bc867f9ba to http://192.168.178.151:8123/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
'''

cause of SSL http:// won't work.

**Comment by Gerrett84** [comment]
Unfortunately it also works in version 2024.1.9 

'''
[HPM] Error occurred while proxying request 192.168.178.151:5050/api/camera_proxy/camera.doorbell_repeater_405c?token=d874904deddd82b67e76fcb8fa8c1494f9e44ab72e91a90999b7047bc867f9ba to http://192.168.178.151:8123/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
'''

cause of SSL http:// won't work.
