### ISSUE TITLE
Pages slider cuts off on mobile view

### ISSUE THREAD

**Issue by Xitro01** [matt8707/ha-fusion#279]
![IMG_0440](https://github.com/matt8707/ha-fusion/assets/19844787/a5bfe898-4f50-4830-8a98-aab97716e3d6)

As you can see in the screenshots above, the pages slider cuts of somewhere half way, while there is enough room for some more text.

Viewing this from an iPhone 15 Pro.

**Comment by matt8707** [comment]
Mobile support has not yet been implemented; you can open issues regarding it once it is.

**Comment by Xitro01** [comment]
> Mobile support has not yet been implemented; you can open issues regarding it once it is.

I saw some other issues regarding mobile view that were solved, so I thought this would be a great addition. But I certainly will.
Not actively using this dashboard, but I'm here to help straighten out the bugs. I see a lot of potential and might move towards this dashboard as it further develops.

Thanks so far!
