### ISSUE TITLE
After updating to 2024.1.8 can no longer authenticate (500 Internal Server Error)

### ISSUE THREAD

**Issue by willsanderson** [matt8707/ha-fusion#285]
Cannot proceed past Fusion auth window after updating to 2024.1.8. Fusion logs show possible issue with hassURL configuration, and browser console logs show a "500 Internal Server Error." Multiple attempts to completely uninstall and reinstall Fusion have been made, but same issue persists.

<img width="1088" alt="Screenshot 2024-01-26 at 9 53 55 AM" src="https://github.com/matt8707/ha-fusion/assets/8596886/7480d2bd-50c0-4b3e-b365-8a2d6b8a9724">

<img width="1281" alt="299821427-40c5eb8a-ec7e-4f24-bcf5-b1f3483ee61e" src="https://github.com/matt8707/ha-fusion/assets/8596886/62994988-9995-4a13-aff2-36d64647dc1e">

**Comment by domored** [comment]
Same for me with https://local_ip:8123

**Comment by matt8707** [comment]
Yeah, undefined flow_id, I get this on my rpi but not in docker or vm
