### ISSUE TITLE
After updating to version 2024.1.8 there is no ip HA in the add-on configuration

### ISSUE THREAD

**Issue by wda06** [matt8707/ha-fusion#288]
After the update, it does not connect to HA, apparently because the ability to set an IP address in the configuration has disappeared.

![Screenshot_20240126_084654_io homeassistant companion android](https://github.com/matt8707/ha-fusion/assets/69405007/6b9bbc5e-891d-4d00-a998-b92827834bdd)
![Screenshot_20240126_084605_io homeassistant companion android](https://github.com/matt8707/ha-fusion/assets/69405007/cc2e6eb1-cb41-4567-90ad-7908c868b8aa)

**Comment by lukeplus** [comment]
The same issue is happening to me，The value of hassUrl is incorrect，But there is no entry point to modify this value.

**Comment by notorioustubze** [comment]
Click edit in YAML Sent from my iPhoneOn 26 Jan 2024, at 08:48, lukeplus ***@***.***> wrote:﻿
The same issue is happening to me，The value of hassUrl is incorrect，But there is no entry point to modify this value.

**Comment by saya6k** [comment]
I'm also having same trouble. It is not possible to customize already configured hass_url. No way to customize this any more.

**Comment by matt8707** [comment]
I'm working on fixing this
