### ISSUE TITLE
Best way to contribute

### ISSUE THREAD

**Issue by fabianluque** [matt8707/ha-fusion#29]
Congrats on getting this out there for anyone to see, it's a really great step in providing a much better dashboard design for HA.

I'm a web developer and I'm wondering what's the best way to contribute right now to this project. Where do you need the most help right now?

Of course I have my own preferences and priorities but just wanted to reach out and see what would benefit you and the project the most in this early stage.

**Comment by matt8707** [comment]
Thanks, any of the feature requests really. What do you want to work on?

**Comment by fabianluque** [comment]
Ok, I’ll start with the cover one.

**Comment by matt8707** [comment]
Nice, thanks

**Comment by matt8707** [comment]
I've added PROGRESS.md, there are probably other domains that I've missed
https://github.com/matt8707/ha-fusion/blob/main/PROGRESS.md

**Comment by janiskelemen** [comment]
@matt8707 I think we can move this to the discussion board. I'll open a new thread there so this issue can be closed.

**Comment by matt8707** [comment]
Alrighty
