### ISSUE TITLE
Tab key does not advance to the next field (password field) in the authentication pop-up

### ISSUE THREAD

**Issue by meanaverage** [matt8707/ha-fusion#290]

**Comment by meanaverage** [comment]
Nevermind (maybe) -- this seems to be a problem with viewing Fusion through the Home Assistant MacOS app. Tab key does not function at all in any modal. Seems like a Home Assistant app incompatibility.

**Comment by matt8707** [comment]
Yup, it's a safari "feature"

https://github.com/matt8707/ha-fusion/blob/main/src/lib/Modal/trapFocus.ts
