### ISSUE TITLE
FR: 'Keep me logged in' option to remain loggin in while reload

### ISSUE THREAD

**Issue by saya6k** [matt8707/ha-fusion#303]
Now I'm condidering using Fusion as my main Kiosk dashboard.

However in Fully-Kiosk or add-on or browser, log in session finished when reload.

Home Assistant log in page have option Keep me logged in.

Make Keep me logged in option.

**Comment by matt8707** [comment]
Auth is already saved?

**Comment by saya6k** [comment]
OK, I cleared my issue.
addon 2024.1.10
core 2024.1.5
In external access like reverse proxy or RFC1918, `ERR_HASS_HOST_REQUIRED` occurs.
But in Home Assistant Add-on ingresss scenario it works perfect.
