### ISSUE TITLE
After the latest update (2024.01.10) there is an error in the web interface ERR_HAS_HOST_REQUIRED

### ISSUE THREAD

**Issue by wda06** [matt8707/ha-fusion#304]
After the latest update (2024.01.10) there is an error in the web interface ERR_HAS_HOST_REQUIRED
![photo_2024-01-28_05-12-35_result](https://github.com/matt8707/ha-fusion/assets/69405007/34abb136-1e39-488e-b86e-3af05cda1b86)
In this case, it is impossible to re-login; when you click delete, it throws you to the web without logging out of your account.
![photo_2024-01-28_05-29-16_result](https://github.com/matt8707/ha-fusion/assets/69405007/565a5977-48eb-4b48-9411-f316f804ae2e)

Yes, and in the configuration, as it once was, there is no way to specify the IP of Home assistant

**Comment by wda06** [comment]
In my opinion, this message disappears if you enable the "keep me logged in" option
![HA](https://github.com/matt8707/ha-fusion/assets/69405007/8e2a83da-149f-47f5-b988-7f5d0ce86e07)

**Comment by t0bse** [comment]
ingress works for me
if i use the fusion port i get this error, too

**Comment by brunopiola** [comment]
I've the same problem. After update 2024.1.10 the message specified wda06 appears where i use the external port of fusion.

**Comment by natebest2000** [comment]
I'm experiencing this issue but only on my wall ipad.  On my phone and my laptop no error and everything functions as expected.  The ipad uses the internal connection for HA but I experienced the same issue when testing external connection also.  My phone and laptop tested both internal and external.

**Comment by larsoss** [comment]
Fixt in v2024.1.11
