### ISSUE TITLE
2024.01.10 - if SSL enabled Camera ist unavabile 

### ISSUE THREAD

**Issue by Gerrett84** [matt8707/ha-fusion#306]
As a Hassio addon function everything, I go via the IP:Port, the camera is not available.

```
[HPM] Error occurred while proxying request 192.168.178.151:5050/api/camera_proxy/camera.doorbell_repeater_405c?token=ec973hbfhcsds5435dd534c67ab to http://192.168.178.151:8123/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while proxying request 192.168.178.151:5050/local/gerrett84.png to http://192.168.178.151:8123/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

http:// should be https://

**Comment by matt8707** [comment]
I think SSL needs to be added to the addon configuration

**Comment by Gerrett84** [comment]
In the addon you should be able to select whether “hass_url” starts with http:// or https://. It may also be possible to automatically detect whether hass_url uses SSL or not.
As far as I can see (For example in server.js), http:// is always specified here.

The addon itself shouldn't need an SSL configuration for this, right?

**Comment by matt8707** [comment]
The hass_url is just the url of your instance. Do you access your internal network using https?

**Comment by Gerrett84** [comment]
> The hass_url is just the url of your instance. Do you access your internal network using https?

Yep, I also use https in my internal network. There has been no reason to change anything here so far. But if you don't plan support for this, I will think about a SSL Proxy .

**Comment by Gerrett84** [comment]
2024.4.0 Fixed it
