### ISSUE TITLE
FR: Modal timeout

### ISSUE THREAD

**Issue by anarion80** [matt8707/ha-fusion#308]
Please consider an automatic closure of any open modal after some period of inactivity.

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/pull/141

**Comment by anarion80** [comment]
@matt8707 continuing here - is there any way now or a plan to have similar event to navigate directly to a certain view? The use case would be like with popups - when the screensaver kicks in, just move to the default view.

**Comment by matt8707** [comment]
I think that with the fullykiosk integration you can set a url in same automation as close popup

**Comment by anarion80** [comment]
Indeed, it works. Thanks!
