### ISSUE TITLE
Climate Control is no longer displayed since update

### ISSUE THREAD

**Issue by patricknitsch** [matt8707/ha-fusion#314]
Since update I don't see the arrows for changing the temperature.

![image](https://github.com/matt8707/ha-fusion/assets/114565561/bc005cf1-3218-4563-9a95-e3a46222354d)

Tested it in HA App on IPhone and in Safari Browser

**Comment by Marc3l1988** [comment]
I dont have any problems with that. Everything seems to be working fine.
![image](https://github.com/matt8707/ha-fusion/assets/60409746/7f3e31b1-89a1-4fde-9839-36d477e806ac)

**Comment by patricknitsch** [comment]
Also Tested it on Edge Browser. The same situation. The arrows are not visible.

@Marc3l1988: Which Version so you have?

**Comment by Marc3l1988** [comment]
@patricknitsch 

HA Versions:
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

HA-Fusion Version: 2024.1.11
Using Browser: Chrome
Also tested it on my mobile phone without any problems.

**Comment by patricknitsch** [comment]
That's interesting. I also tested it in Chrome Browser and Safari on Macbook. There it works. It looks like it's only a problem on my I Phone
