### ISSUE TITLE
FR: Add password protection to edit and raw config buttons. 

### ISSUE THREAD

**Issue by TKpizza** [matt8707/ha-fusion#320]
Would love to password protect the edit and raw config editor buttons. I have kids that like to touch things and they will def mess everything up.

**Comment by matt8707** [comment]
Have you read this? https://github.com/matt8707/ha-fusion?tab=readme-ov-file#menu

> To disable the menu button, append the query string ?menu=false to the URL. This is useful when you want to avoid unwanted changes to your dashboard, such as on wall-mounted tablets.

**Comment by TKpizza** [comment]
No, I did not. Thank you. That solves my problem.
