### ISSUE TITLE
Issue with Displaying Map Maptiler

### ISSUE THREAD

**Issue by Mantinum** [matt8707/ha-fusion#321]
Hello,

I'm encountering an issue with my project where the map does not display when I click on a family member's profile. I've properly integrated the Maptiler API key into the additional modules, but this hasn't resolved the issue.

![Capture d’écran 2024-01-31 à 18 06 07](https://github.com/matt8707/ha-fusion/assets/16976303/496230fc-2bb1-4e5a-8c60-3c4f3853ef7b)

Here's a brief overview of the problem:

Expected Behavior: Clicking on a family member's profile should display a map.
Actual Behavior: The map does not appear upon clicking.
Steps to Reproduce:
Navigate to a family member's profile.
Click on the profile to trigger the map display.
Observe that the map does not appear.
I've checked the API integration and ensured that the key is correctly added, but the map still doesn't load. Any guidance or suggestions on how to resolve this would be greatly appreciated.

I apologize for any mistakes in my English, as it's not my first language. Thank you in advance for your help!

Best regards,

**Comment by abeksis** [comment]
Access the log area and see, maybe there is some log or error that indicates the problem.

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/310
