### ISSUE TITLE
FR:Navigation card

### ISSUE THREAD

**Issue by Bandy325** [matt8707/ha-fusion#322]
First of all, thank you for your efforts in this dashboard!  I like to use the navigation card for the sidebar.  What I would like here is if you could organize the 'views', perhaps in alphabetical order, or according to your own layout?

Since I am not computer-technical myself, I don't know if this is feasible.  Or maybe it is already planned.

**Comment by matt8707** [comment]
Isn't it more logical for the order of navigation links to match the order in which you've arranged your views? The views are drag and drop

**Comment by Bandy325** [comment]
> Isn't it more logical for the order of navigation links to match the order in which you've arranged your views? The views are drag and drop

I had not used that method before (make views invisible right away) and honestly I didn't know it was possible that way.  This way is a different view but with the same result in the end.  Thanks!
