### ISSUE TITLE
Camera frame adjustment

### ISSUE THREAD

**Issue by MrOlof** [matt8707/ha-fusion#33]
Camera does not auto adjust to the frame:
Camera frame goes outside the frame when opening.

![image](https://github.com/matt8707/ha-fusion/assets/100124559/efad321c-3b1f-4017-90cd-c74951da7265)

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/pull/32/commits/bf5fda162d7ebe82c8caa1ed625609a691c2fc29

**Comment by MrOlof** [comment]
Now it fits the frame but you still have to scroll.
It would be great if it would auto-adjust to fit the popup rather than the popup adjusting to the camera and adding scroll.

![image](https://github.com/matt8707/ha-fusion/assets/100124559/660d3a9d-f839-4a3a-9433-2c4f1cf23b49)

**Comment by thundergreen** [comment]
same here 

![image](https://github.com/matt8707/ha-fusion/assets/13320319/c341eb24-6083-4acc-b44d-779dd4bb3cfd)
