### ISSUE TITLE
FR: Support for reload/refresh page event

### ISSUE THREAD

**Issue by h3nrytan** [matt8707/ha-fusion#330]
Hello.

Possible to have similar automation event as "close_popup" for reload/refresh page?

Like browser mod: refresh

Will be handy to update multiple dashboard with kiosk app on IOS.

**Comment by matt8707** [comment]
What is kiosk app on iOS? I know in fullykiosk you can refresh page from ha

**Comment by h3nrytan** [comment]
@matt8707

Hello

I'm using Kiosk - Fullscreen Browser https://apps.apple.com/us/app/kiosk-fullscreen-browser/id1544947623

Unfortunately Fully Kiosk Browser is only available on Android. 

I supposed the Kiosk app and various browsers on iOS do not have the feature as Fully Kiosk Browser due to Apple's restriction.
