### ISSUE TITLE
FR: Support list attribute be seen as table in button popup

### ISSUE THREAD

**Issue by saya6k** [matt8707/ha-fusion#332]
<img width="489" alt="스크린샷 2024-02-02 10 52 21" src="https://github.com/matt8707/ha-fusion/assets/63517312/2840c210-8ee8-4c52-953b-97b3e1e9e315">
<img width="484" alt="스크린샷 2024-02-02 10 52 37" src="https://github.com/matt8707/ha-fusion/assets/63517312/1277038b-88d5-4b32-a7fd-94b198778abf">

There are sensors that have list as attributes in Home Assistant.

I have sensor.grocy_*, sensor.seventeentracks_* etc.

But when I assign those attribute as button attribute, it shows like above.

It will be super useful if sensor button can show list attribute as table in popup.

**Comment by matt8707** [comment]
I'm considering introducing templates that will eliminate the attributes dropdown. This issue will be addressed by the introduction of templates, so it will not be worked on.
