### ISSUE TITLE
Incorrect Port Display When Starting the Addon

### ISSUE THREAD

**Issue by kenhoppla** [matt8707/ha-fusion#333]
I attempted to start the addon using a custom port. However, in the log, it displays the old port (8099), whereas the addon is actually using the custom port. As a result, Home Assistant fails to recognize the addon as started, even though it is indeed running. Access to it is possible via homeassistant.local:customPort.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
[HPM] Proxy created: /  -> http://192.168.178.30:8123
ENV HASS_URL: http://192.168.178.30:8123
ENV PORT: 8099
ENV ADDON true
``` 

<img width="903" alt="image" src="https://github.com/matt8707/ha-fusion/assets/126197899/6a1b8130-4886-4cd6-b081-07efc30f3cb3">

<img width="903" alt="image" src="https://github.com/matt8707/ha-fusion/assets/126197899/eeed66fc-99c3-491a-9e6b-1fa8c89c2073">

<img width="903" alt="image" src="https://github.com/matt8707/ha-fusion/assets/126197899/ffaead61-e71b-4f10-9d5c-e843a70327e2">

**Comment by matt8707** [comment]
This is an outdated version. The authentication flow was reverted, so I'm closing this.
