### ISSUE TITLE
FR: Loading Splash Page

### ISSUE THREAD

**Issue by h3nrytan** [matt8707/ha-fusion#334]
Currently when we load the page, entities are unavailable till the page fully loads. 

Not a big deal but a loading splash page is a nice to have.

Current view when page is loading:-
![2](https://github.com/matt8707/ha-fusion/assets/3590384/61b651bf-b238-4d78-8f33-f7bab19eb268)

Sample from default Home Assistant:-
![1](https://github.com/matt8707/ha-fusion/assets/3590384/30f4ab81-6abd-445b-be9e-8e79710bbe12)

**Comment by matt8707** [comment]
This article reflects some of my opinions

https://medium.com/@adityabhaskar/app-splash-screens-the-good-the-bad-and-the-ugly-f3248b549be7

**Comment by h3nrytan** [comment]
One of the comments in the article:- 

"Much like animations on a mobile OS, splash screens are there to hide a delay. It’s to comfort the user that something is happening rather than appearing to hang while it loads resources. Small apps may benefit from a lack of a splash screen, but it’s a necessary evil for resource heavy ones."

Hope you may reconsider to have a way to show ha-fusion is "loading". 

I'm planning to have my elders using ha-fusion. At times our WIFI connectivity ain't great, causing ha-fusion to take a little longer to load. I can picture my elders tapping on the buttons thinking it's broken while it's actually loading 😆
