### ISSUE TITLE
Lost all existing configuration / or crash 

### ISSUE THREAD

**Issue by wilksy** [matt8707/ha-fusion#338]
![Screenshot_20240203-215527](https://github.com/matt8707/ha-fusion/assets/27734612/8424f475-5478-48ef-9ae3-34f59c869908)

Nothing working / can't view yaml / can't edit any existing objects or add new.

**Comment by xrolfex** [comment]
This looks more like the connection to home assistant is not working.

**Comment by wilksy** [comment]
> This looks more like the connection to home assistant is not working.

No. 

The rest of my instance is 100% working, automations runnings and default dashboards perfectly.

**Comment by wilksy** [comment]
Fixed by using reverse proxy on Fusion HA URL, even when using on local network.
