### ISSUE TITLE
HA Fusion - External Access

### ISSUE THREAD

**Issue by h3nrytan** [matt8707/ha-fusion#343]
Hello

Example of my setup for external access as below:-
Home Assistant external URL: https://ha.example.com pointing to local IP: 10.0.0.10:8123
Ha-Fusion external URL: https://hafusion.example.com pointing to local IP: 10.0.0.10:5050

--

With docker setup, I'm able to include https://ha.example.com in HASS_URL settings. 

That allows me to authenticate and use ha-fusion via https://hafusion.example.com outside of my home. 

--

With Home Assistant Add-ons setup, I could only change the port number under configuration. 

Whenever I login to https://hafusion.example.com, the authentication page redirects with the default URL https://hafusion.example.com/auth... that causes error because that's not my Home Assistant external URL. 

No issue with local IP access and authentication..

--

I could only think of having the option to configure HASS_URL in Home Assistant Add-ons setup to resolve the authentication error for external access. 

Please do let me know if there is another way of setting.

Thanks!

**Comment by thundergreen** [comment]
Sorry that I jump in but fusion has ingress support. so no external access specific needed for that. Just call home assistant via external address and chose fusion via ingress....

**Comment by h3nrytan** [comment]
> Sorry that I jump in but fusion has ingress support. so no external access specific needed for that. Just call home assistant via external address and chose fusion via ingress....

Hello. I notice that approach does not allow me to set Fusion Dashboard as my default because it's not lovelace therefore external access direct to Fusion Dashboard is needed for me. Also I'm preventing my users to meddle with the HA sidebars.

**Comment by h3nrytan** [comment]
Refer to https://github.com/matt8707/ha-fusion/discussions/412#discussioncomment-9210351 for alternative solution.
