### ISSUE TITLE
Button showing an entity with 'On' state doesn't show as on in the dashboard

### ISSUE THREAD

**Issue by realroywalker** [matt8707/ha-fusion#352]
I have a bunch of buttons on my dashboard and spotted the one linked to my heating sensor doesn't show as 'on' in the dashboard when the entity is on.. I'm not sure but I wonder if it's because the Wiser Integration sets the state to **O**n not **o**n - as all my other entities show correctly in the dashboard and they are all lower case..

See here:
![image](https://github.com/matt8707/ha-fusion/assets/486860/1ddc717d-37df-43e5-97d5-683b58ef0755)

As a side note it would be really cool to be able to have the rule which decides if something is on or not in the dashboard as a template as part of the button config (like the new template options just added - which ROCK by the way!) - I have a number of sensors (eg my Gas Tank level) which I'd like to highlight as 'On' when it's below 30% for example.

**Comment by matt8707** [comment]
note to self

1. set state toLowerCase()
2. related to https://github.com/matt8707/ha-fusion/issues/353
