### ISSUE TITLE
FR: Static/Independent Sidebar

### ISSUE THREAD

**Issue by LionCityGaming** [matt8707/ha-fusion#354]
Would love to have the sidebar _not_ scroll up or down together with the main body content and remain static in its place.

**Comment by matt8707** [comment]
That breaks top drawer and mobile layout and is not something I'll add, 

but you can try it youself with custom_javascript.js in settings

```js
console.debug('🎉 Custom JavaScript file loaded!');

// select the <aside> element
const asideElement = document.querySelector('aside');

// add styles
if (asideElement) {
  asideElement.style.position = 'fixed';
  asideElement.style.height = '100vh';
  asideElement.style.overflowY = 'auto';
}
```
