### ISSUE TITLE
Popup menu/toggle behavior of button

### ISSUE THREAD

**Issue by HAMarkus** [matt8707/ha-fusion#355]
Hello, 
first of all, great project.
Would it be possible to realise the same button behavior as in your last project?

Right now I have to push the symbol of the button to toggle the state and if I push the rest of the field, the popup menu opens.
The behavior in your other project was very user friendly in my opinion. 
Means: toggle the state in the complete area of the botton, double tap for popup menu and maybe also some kind of slider functionality as you had.

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/44
