### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by Bandy325** [matt8707/ha-fusion#36]
I am setting up the dashboard and am already very impressed with how it looks and how easy it is to use.

I only run into the following... If I create a "section" and add buttons there, I cannot drag them to a horizontal stack. If I drag the button to the horizontal-stack nothing happens, when I release the button it shoots back to the "section".

Another issue has been opened that is similar to this, but the temporary option given there does not work for me either.

I am using version: 2023.12.8

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
listening on port 5050
env HASS_URL undefined
env ADDON true
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml
No existing file found for ./data/configuration.yaml

**Comment by matt8707** [comment]
you cant drag buttons to stacks, stacks are for sections

**Comment by naseemr** [comment]
I cannot drag a section to horizontal stack
