### ISSUE TITLE
FR: Implement hls camera

### ISSUE THREAD

**Issue by pimp1310** [matt8707/ha-fusion#369]
Hello,

All my Cameras only show a Loading circle, and when i click on them there is no Live View,only the loading circle.

here are the infos of my cams, when you need more infos i provide them.

THANK YOU

CAM 1
`access_token: XXXX
frontend_stream_type: hls
entity_picture: >-
  /api/camera_proxy/camera.192_168_0_27?token=XXX
icon: mdi:camera
friendly_name: RTSP Kamera Kinderzimmer
supported_features: 2`

CAM2

`access_token: XXXXX
entity_picture: >-
  /api/camera_proxy/camera.192_168_0_116?token=XXXX
friendly_name: "192_168_0_116"
supported_features: 0
`

CAM3 
`access_token: XXXX
entity_picture: >-
  /api/camera_proxy/camera.esp32_cam?token=XXX
friendly_name: esp32_cam
supported_features: 0`

CAM4

`access_token: XXX
frontend_stream_type: hls
entity_picture: >-
  /api/camera_proxy/camera.192_168_0_27?token=XXXX
icon: mdi:camera
friendly_name: RTSP Kamera Kinderzimmer
supported_features: 2`

**Comment by matt8707** [comment]
is it just cameras or images too?

**Comment by imMrRAW** [comment]
I have the same issue now.

**Comment by pimp1310** [comment]
> is it just cameras or images too?
hi
what do you mean ?

i see a still image, for example here from 19:26 but its 19:29

![cam](https://github.com/matt8707/ha-fusion/assets/6306057/082c29a5-055c-467a-8417-6f04b54c248e)

**Comment by matt8707** [comment]
What happens if you navigate to `/api/camera_proxy/camera.192_168_0_116?token=XXXX` directly in URL. Does the stream work?

**Comment by matt8707** [comment]
> What happens if you navigate to /api/camera_proxy/camera.192_168_0_116?token=XXXX directly in URL. Does the stream work?

**Comment by mucki12** [comment]
Sorry @matt8707 
No navigating to the cam url does not give me a live stream, but the latest still image.

e.g.:
Cam with entity camera.ring_garten in HA:
```
access_token: XXX
frontend_stream_type: hls
entity_picture: >-
  /api/camera_proxy/camera.ring_garten?token=XXX
friendly_name: Ring Garten
supported_features: 2
```

Navigating to http://HA-IP:8099/api/camera_proxy/camera.ring_garten?token=XXX gives me the still image

Using camera.ring_garten as entity in HA with the "Picture glance card" gives me the still image and with click on this image it gives me a live stream in a smaller popup window.

**Comment by matt8707** [comment]
does url `camera_proxy_stream` work?
* post a screenshot of /api/camera_proxy_stream/camera.ring_garten?token=XXX
* post any browser console error in fusion

**Comment by mucki12** [comment]
The URL http://192.168.2.189:8123/api/camera_proxy/camera.ring_garten?token=XXX delivers a still image and the URL http://192.168.2.189:8123/api/camera_proxy_stream/camera.ring_garten?token=XXX just a blank white side.
(no matter whether the Fusion or the HA port is used)

Unfortunately I don't know how the "Picture glance card" displays a still image on one side and shows the live stream when clicked?

Sorry, but I'm not very familiar  with the developer tools of a browser.

Fusion:
![Übersicht](https://github.com/matt8707/ha-fusion/assets/92673795/12fef8cb-f000-4a71-a112-55d9b00f4ee6)

Fusion clicked:
![Pasted Graphic 17](https://github.com/matt8707/ha-fusion/assets/92673795/bc100e1d-d40b-4ff1-b115-4315f7e79d22)

HA:
![Pasted Graphic 15](https://github.com/matt8707/ha-fusion/assets/92673795/d1457efb-8eda-4bc2-9933-e1184550b513)

HA clicked (live-stream):
![Ring Garten](https://github.com/matt8707/ha-fusion/assets/92673795/7a72979c-04bb-4a9e-8994-fe6d9d3bce0d)


Developer Tools (sorry, don't know much about it):
![Pasted Graphic 22](https://github.com/matt8707/ha-fusion/assets/92673795/2fc9ee27-0bc3-4771-91f3-3dfef5a43d2f)


Browser URL http://192.168.2.189:8123/api/camera_proxy/camera.ring_garten?token=XXX (just a still image):
![Pasted Graphic 20](https://github.com/matt8707/ha-fusion/assets/92673795/a7e64e51-a32e-49b7-a99e-c31910ea1dc2)

**Comment by mucki12** [comment]
This is shown with browser developer tools regarding the pop-up of picture glance card (don't think this will help....)

<video poster="http://192.168.2.189:8123/api/camera_proxy/camera.ring_garten?authSig=really_long_token;width=580&amp;height=0" autoplay="" playsinline="" controls=""><source type="video/mp4" src="blob:http://192.168.2.189:8123/token"></video>

**Comment by matt8707** [comment]
note to self: need to get m3u8
https://developers.home-assistant.io/docs/api/native-app-integration/sending-data?_highlight=stream#stream-camera

**Comment by TheOpsMgr** [comment]
Ditto as per my discussion thread here.

https://github.com/matt8707/ha-fusion/discussions/416#discussioncomment-8831499

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2024.5.0
