### ISSUE TITLE
[Enhancement] Custom brand icons

### ISSUE THREAD

**Issue by imMrRAW** [matt8707/ha-fusion#377]
In HACS there's "Custom brand icons", would be super neat if it was possible to use these - as they contain a lot of good icons for example Aqara, Cars and such.

I tried to use it with this icon: phu:aqara-contact
But ended upp getting an question mark as icon.

This is what is looks like using the regular view in Home Assistant.

![image](https://github.com/matt8707/ha-fusion/assets/56786847/0c73ba36-8d5f-433a-9862-f0e3f9571139)

https://github.com/elax46/custom-brand-icons

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/145

https://icon-sets.iconify.design/cbi/
