### ISSUE TITLE
(FR) - Ability to hide section titles to save space

### ISSUE THREAD

**Issue by leacho73** [matt8707/ha-fusion#378]
Is it possible to hide the view titles to allow closer packing of cards - for example, I have a horizontal stack at the top of my dashboard which has a large space at the top due to the section spacing, even though I have nothing in there.

**Comment by matt8707** [comment]
Edit UI -> Appearance -> Navigate Hidden

**Comment by leacho73** [comment]
Hi @matt8707 - thanks for the quick response.

That's sorted the views - but the section titles are still causing a gap :)
