### ISSUE TITLE
FR: Ability to align items in Sidebar

### ISSUE THREAD

**Issue by leacho73** [matt8707/ha-fusion#380]
It would be great if there was the ability to align (left/center/right) any item in the sidebar, with everything justified to the left, the right hand side of the sidebar looks a little bit empty.

**Comment by matt8707** [comment]
Use custom_javascript.js to do custom styles, themes might adress this in the future

**Comment by leacho73** [comment]
Thanks @matt8707 - are there any docs for the customer_javascript I can reference please?

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/354
