### ISSUE TITLE
Response Code 400 from /auth/token

### ISSUE THREAD

**Issue by sandstormkeshav** [matt8707/ha-fusion#406]
Hello! First of all this dashboard looks amazing and I am excited to get this working!
I recently set this up with the docker compose file in the repository, I get redirected to my Home Assistant instance's login page and upon signed in I come back to the Fusion page.
When clicking add, the object is grayed out:
![image](https://github.com/matt8707/ha-fusion/assets/8977997/8ed57066-7752-438b-8ec3-2838a4c2e869)

Looking at the network tab, I see many 400's on requests to /auth/token with a response of: {"error":"invalid_request","error_description":"Invalid code"}
![image](https://github.com/matt8707/ha-fusion/assets/8977997/9ea7a366-0c95-4617-9dd7-61fdf63e7b99)

Do you have any ideas on what might be causing this?

**Comment by xrolfex** [comment]
Not sure on the token issue, I will see if I can reproduce it; but in order to add an object you must first add a section.

**Comment by Itsememario** [comment]
I think i noticed you problem. Its actually very simple: add an section, that will fix it. Then you can add items!

**Comment by Itsememario** [comment]
> > Not sure on the token issue, I will see if I can reproduce it; but in order to add an object you must first add a section.
> 
> Thank you for letting me know, the object button does show up when I add a section however clicking it does not bring up a page to add anything.
> 
> In the browser's console I see a lot of ERR_INVALID_AUTH created by this part of the application:
> <img width="331" alt="image" src="https://github.com/matt8707/ha-fusion/assets/8977997/c67f41f5-9566-4bf6-a71d-7b84d93bac2c">
> 

Hmm looks like an Issue from hass try Customizing the addon and using it without a ingress. It looks like it isnt Connecticut to the homeassistant device list. Can you Provide more Infos and can you tell me if the addon detects any device
