### ISSUE TITLE
Add Legacy Browser Support

### ISSUE THREAD

**Issue by jake1970** [matt8707/ha-fusion#407]
Any chance that you would be able to configure to allow for legacy browsers, I'm trying to run/view on iOS 12 safari and am being displayed an empty black screen.

**Comment by hansherlighed** [comment]
What are the requirements for this to work on older browsers? Trying to use this in safari and chrome on an Ipad with IOS 12.5.7 and it just shows a black screen. I'm guessing that the browsers available on this IOS version are to old, but what version is the minimum?

**Comment by clutchthrower** [comment]
Don’t know if it’s a legacy browser issue. Getting just a black screen on my iPhone 15 Pro Max using Safari, external url, fusion port open, Cloudflared,

**Comment by matt8707** [comment]
I can't test it, but see if adding https://github.com/matt8707/ha-fusion/commit/40d7a8688d5321757ad7b9d0d0d69e51e468e16f makes a difference
