### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by amedello** [matt8707/ha-fusion#409]
Please, how i can access from external url to dashboard? I use  docker installation and cloudflare domain. If i set a second level url like hafusion.myhome.org redirect to myinternalip:5050 i have mixed content problem and no script was loaded. I not find how to access to dashboard throught my homeassistant installation.

**Comment by sShrek1** [comment]
For clarification - I am also new to this ingress stuff.

The url shouldn't be localip:5050. It should rather be your home Assistant up:8123/{ha-fusion-hostname}/...

So if you already exposing your HA then just add the ha-fusion path..
