### ISSUE TITLE
Color bug when use customized template

### ISSUE THREAD

**Issue by dlangamer** [matt8707/ha-fusion#420]
When I use a customized template for a certain entity in my currently language, the entity icon does not respect the selected colors. If I customize the status in the English language, everything works as expected.

![image](https://github.com/matt8707/ha-fusion/assets/30659252/935d9b8d-526f-40e7-acfc-8a25a8b0f656)
![image](https://github.com/matt8707/ha-fusion/assets/30659252/49dc87be-8783-4559-aff7-aef0e6527dc8)
![image](https://github.com/matt8707/ha-fusion/assets/30659252/d6e19dc0-fa92-452b-b78d-6007e08ee413)
![image](https://github.com/matt8707/ha-fusion/assets/30659252/815a0be3-6c76-4648-9d65-6dd859f74891)
![image](https://github.com/matt8707/ha-fusion/assets/30659252/9f5aec9d-437a-417a-8e6e-088e9cc33b86)

**Comment by matt8707** [comment]
Icon color only applies to entities that are turned on, 
but you can use the 'icon color template' where you can set 'off state' as well

**Comment by filikun** [comment]
> Icon color only applies to entities that are turned on, but you can use the 'icon color template' where you can set 'off state' as well

I'm sorry to revive this but how do you mean "set 'off state'" in the icon color template?

**Comment by matt8707** [comment]
Edit button > Color > Template

![Skärmavbild 2024-05-29 kl  16 31 24](https://github.com/matt8707/ha-fusion/assets/36163594/7bf9e144-37f4-47cb-a03b-abb8426594f9)
