### ISSUE TITLE
Enhancment of the cards

### ISSUE THREAD

**Issue by Itsememario** [matt8707/ha-fusion#422]
(Label: Enhancment)
Hey there! I really love this project! (Even tough its dying sadly) can there be maybe... A bit more?
I know this what you did is already insane but why cant you add the objects from the sidebar? Isn´t the sidebar usually the option that only is needed if you want to show permanent things like for example the clock or navigation? It would be super duper n9ice and cool if we could see all of the current widgets from the sidebar also in the main part as i really need tamplates for example because othere types dont really work for me. Thanks: Charged! @matt8707

**Comment by ItsCharged** [comment]
@matt8707 Wdym whit duplicate? Can you mention the other issue and what happend?
