### ISSUE TITLE
Installing via Docker but on Synology DSM?

### ISSUE THREAD

**Issue by Fr3d3rick83** [matt8707/ha-fusion#423]
Hi,

I´m using HA within Docker but on my Synology NAS, how can I install HA Fusion there?

Thanks.

**Comment by jcreynolds** [comment]
Check out the docker compose section of this guide:   https://www.smarthomebeginner.com/synology-docker-media-server/

Its not HA-Fusion specific but in general this is how you can install it via docker compose on your Synology NAS.

**Comment by matt8707** [comment]
I'm using a synology nas as well, ssh and use docker-compose
https://github.com/matt8707/ha-fusion?tab=readme-ov-file#docker

**Comment by brunoamorim** [comment]
@matt8707 I am using Synology NAS as well, with docker compose. I've installed the HA Fusion but can't communicate with the Home Assistant. HA doesn't find the HA-Fusion but I can access to HA-Fusion through http. There are other configurations that I must do?
