### ISSUE TITLE
Add media card like in the présentation video

### ISSUE THREAD

**Issue by dimed89** [matt8707/ha-fusion#424]
Hello,

Thanks for ha fusion its really really good job.

I want to set up the media card with plex and my media device to show the pictures of the last movies/tv series but I really don’t understand how I can do that, can you help me?

**Comment by taillis** [comment]
Hi, 

Try the code below and change the entity ID

`          - type: media
            id: 1366562140725
            conditional:
              - entity_id: sensor.plex_recently_added
                name: Senast tillagt
                icon: mdi:plex
                color: orange
`

**Comment by dimed89** [comment]
Yep thanks, I'm noob with the code... ^^

Do you know how to make the covers of recently added scroll one by one? currently it works but leaving a static cover of the last downloaded film/series

**Comment by taillis** [comment]
Have you configured the integration? If so, there is a attribute called max that you can specify how many items you want to get from the server. [Click here to check it out](https://github.com/custom-components/sensor.plex_recently_added#:~:text=to%20access%20Plex.-,max,-5)
