### ISSUE TITLE
Is it safe to have multiple replicas running in k8s?

### ISSUE THREAD

**Issue by evanfoster** [matt8707/ha-fusion#426]
Hey there!

I'm going to install ha-fusion via the Helm chart, and I was curious if it was safe to run multiple, concurrent replicas. I prefer running things in a highly-available fashion, so I was happy to see `replicas` in the `values.yaml` file. However, I also noticed the persistent storage option. I have `ReadWriteMany` volumes available in my cluster, so I definitely could hook up a PVC to multiple pods. Is this safe to do?

**Comment by disruptivepatternmaterial** [comment]
I've been wanting to do what you have done (move everything to k8s). Do you have some of you setup, configs, etc... you'd be willing share somewhere?

If I helps I have 2 copies of this project running using docker compose on different ports. So should work for k8s fine as you describe.

**Comment by evanfoster** [comment]
> I've been wanting to do what you have done (move everything to k8s). Do you have some of you setup, configs, etc... you'd be willing share somewhere?
> 
> If I helps I have 2 copies of this project running using docker compose on different ports. So should work for k8s fine as you describe.

Hey @disruptivepatternmaterial,

I can share a bit of what I've done, although it'll be a few days as I'm currently away from my cluster.

W.r.t. the two copies you're running, are they both sharing the same volume mount for their persistent config? Or do you have two separate volume mounts?

**Comment by matt8707** [comment]
I'm removing the kubernetes section, feel free to create a new repo with instructions and I'll link to that 
https://github.com/matt8707/ha-fusion/commit/1d9018949fcb2531e1053e9d848024fdf376328d

**Comment by evanfoster** [comment]
Understood. I may just do that.

I am still curious about whether or not it's safe to have multiple concurrent processes accessing the data meant to be stored in that volume. It's less a Kubernetes specific question and more of an application design question. I can dig into the app myself and get this info, but I figure it's worth asking. Like, that volume is used for the dashboard configs, right? If so, then I'm guessing there's no sort of locking mechanism in place around reads and writes which would make concurrent access unsafe. That's totally fine, I just don't know if it's used for config or as a cache.

If it isn't safe, then I might try to implement some form of optional leader election. I've never written typescript so I don't know how easy or hard that would be or if you'd be willing to accept a PR for that, but it's something I've considered since I saw your comment yesterday.
