### ISSUE TITLE
Can't configure Sidebar after adding it

### ISSUE THREAD

**Issue by Chakkaaa** [matt8707/ha-fusion#430]
Hi,

I am not able to configure the sidebar after adding it in "Edit UI" mode. I get a white circle in the middle of the screen circeling for ages and nothing happens.
Already reinstalled the Add-on with no success.

Any idea what could be missing?

Thanks

**Comment by Snakzi** [comment]
Same issue here.

**Comment by clipse2004** [comment]
Same problem for me. 
I have now tried various versions, the problem in question occurs from version 2024.1.7 onwards, all versions before that work. 
Now you can't select an addon version in HA, so I've switched to Synology Docker. 
No problems so far

**Comment by ellisriffle** [comment]
Same issue for me. I can edit the main section but if I click edit on the sidebar, I get the white circle that never ends and can't actually do anything else.

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/commit/91f37cce10b534ff137725d9a16560a3b04fcd44
