### ISSUE TITLE
Dashboard does not get updated / refresed after HA 2024.4.0 and 2024.4.1 update

### ISSUE THREAD

**Issue by lbreggi** [matt8707/ha-fusion#431]
Hi! After I updated my HA to 2024.04 version, my fusion dashboard is not refresing / updating anymore. Even the clock is not refreshing the time. i tried from computer, tablet (iOS and Fire OS) and mobile (iOS) and the behavior is always the same. Before the update everything was working perfect.
![Screenshot 2024-04-05 at 9 39 31 AM](https://github.com/matt8707/ha-fusion/assets/25729150/0db1ebe4-1a48-46dd-9865-4331c94fd122)
![Screenshot 2024-04-05 at 9 39 10 AM](https://github.com/matt8707/ha-fusion/assets/25729150/e3804392-863a-4e5e-b2e2-eca65300dda2)
![Screenshot 2024-04-05 at 9 40 25 AM](https://github.com/matt8707/ha-fusion/assets/25729150/e713f9d8-bf43-4336-b5b4-cb382e4b800f)

**Comment by anarion80** [comment]
Same here :( Maybe once every 20 refreshes it works. Once after clearing cookies and local storage and logging again. But then it's the same. No real errors or anything, don't even know where to start debugging :/

**Comment by lbreggi** [comment]
also same behavior on 2024.4.1

**Comment by anarion80** [comment]
For what it's worth, I just built a docker container directly from the latest version on `main` and so far it seems to be working correctly for two days...

**Comment by lbreggi** [comment]
I just deleted my old one, and now I can't  even start to build a new one (dashboaard does not refresh with the items that I'm trying to add).

**Comment by cd1zz** [comment]
Something must have changed with the "weatherforecast" type?   When I remove this from my old/working YAML file it works again:
- type: weatherforecast
    id: 1572700476939
    entity_id: weather.forecast_home_2

Do you guys have one of these entities?

**Comment by anarion80** [comment]
That is very likely. We don't have `forecast` attributes anymore in HA weather entities, we should use `get_forecast(s)` services now:

https://www.home-assistant.io/blog/2024/04/03/release-20244/#backward-incompatible-changes
https://www.home-assistant.io/integrations/weather#service-weatherget_forecasts

**Comment by Snakzi** [comment]
This is probably related to the sidebar:
https://github.com/matt8707/ha-fusion/issues/430

**Comment by NeckBeardPrince** [comment]
> @EvanBarbour3 can you fix it? :-)

I'm pretty sure this project is dead.

**Comment by weaverprojects** [comment]
How do you know that? Maybe he has other things to do. You should just be grateful for what he have achieved so far.

**Comment by NeckBeardPrince** [comment]
> You should just be grateful for what he have achieved so far.

Where did I say I was ungrateful?

> How do you know that?

I didn't say I know it's dead, I said I was "pretty sure" from context clues. The owner hasn't done anything on GitHub in over two months, including zero comments. The number of issues that are open and untouched. PRs that are also untouched.

![CleanShot 2024-04-12 at 06 17 50](https://github.com/matt8707/ha-fusion/assets/6558867/fa616209-9a0f-41b8-a9d3-5f3f7045169e)

**Comment by su2626** [comment]
Pretty sure it's dead. HA came with the same Drag&drop concept which is more or less the same concept than Matt. 

HA Drag&drop UI is far less interesting than the one matt provided but I that will do I guess

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/commit/91f37cce10b534ff137725d9a16560a3b04fcd44
