### ISSUE TITLE
Add Number Entity Set Ability

### ISSUE THREAD

**Issue by benepixx** [matt8707/ha-fusion#442]
Hi Matt, first of all congrats on creating the best HA dashboard ever. Im fully invested in this at this point its my main UI. 

If you find some free time, the number entities only allow you to view their state and not set them. I have quite a number entities in play, both for HVAC temperatures and house batteries that require the ability to set the number entity, I think either a +/- or slider would be helpful for number entities so you can set their value. If this is achievable using using the template editor in the object config please let me know. I may have missed something. 

Cheers.

**Comment by matt8707** [comment]
Just had a look, apparently the "mode" attribute can be `mode: auto`, adding fix in next release.
