### ISSUE TITLE
Without internet icons are not load !

### ISSUE THREAD

**Issue by amirhosseinchoghaei** [matt8707/ha-fusion#468]
Hi there , special thanks for this wonderful project . 

i want to use ha without internet , icons not load in ha-fusion !

please help to use the icons without internet 

thanks

**Comment by matt8707** [comment]
Here's a discussion on the subject https://github.com/matt8707/ha-fusion/discussions/441

**Comment by amirhosseinchoghaei** [comment]
i'm using docker but 99% of mdi icons not working ... 
how can i upload the mdi icons in database ?

**Comment by matt8707** [comment]
Did you read the linked discussion?

**Comment by amirhosseinchoghaei** [comment]
Yes But you said mdi icons is okay ! But they are not .

**Comment by matt8707** [comment]
I didn't say that
