### ISSUE TITLE
Update installation guide

### ISSUE THREAD

**Issue by nagtegaal** [matt8707/ha-fusion#47]
If the installation guide could be updated, perhaps there are more people like me, who are willing to help.
I never have worked with Fusion before, so setting up is the real struggle here…

**Comment by MrOlof** [comment]
You can just add it via custom repo if you simply want to try it out.

https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fmatt8707%2Faddon-ha-fusion

However, if you want to use docker then I think it's best left to people who are devs and know how to.
I could do a guide if people are interested though.

**Comment by matt8707** [comment]
> I could do a guide if people are interested though

I'd like help with this, even if it's just a draft

**Comment by janiskelemen** [comment]
> If the installation guide could be updated, perhaps there are more people like me, who are willing to help.
> 
> I never have worked with Fusion before, so setting up is the real struggle here…

At which point did you get stuck? I could record a screencast if that helps?

**Comment by raffaelevall** [comment]
Hi, if I use docker compose I get the following error:
`
root@docker:~# docker compose up -d
[+] Running 1/1
 ✘ ha-fusion Error                                                              0.3s 
Error response from daemon: Get "https://ghcr.io/v2/": dial tcp 140.82.114.33:443: connect: network is unreachable
`
tks

**Comment by nagtegaal** [comment]
I installed the ha-fusion add-on, which does not give me the experience which is displayed in the video here: https://www.youtube.com/watch?v=D8mWruSuPOM

I do not have the possibilities to add different sections inside a horizontal-stack, nor do I have all the options to add the cards to it. I only have 2 cards, which are button and camera.
That's why I think that the installation/configuration isn't that great.

I'm using Safari 17.2.1 as my browser on MacOS Sanoma 14.2.1

**Comment by janiskelemen** [comment]
> I installed the ha-fusion add-on, which does not give me the experience which is displayed in the video here: https://www.youtube.com/watch?v=D8mWruSuPOM
> 
> 
> 
> I do not have the possibilities to add different sections inside a horizontal-stack, nor do I have all the options to add the cards to it. I only have 2 cards, which are button and camera.
> 
> That's why I think that the installation/configuration isn't that great.
> 
> 
> 
> I'm using Safari 17.2.1 as my browser on MacOS Sanoma 14.2.1

I think the horizontal stack is a bit buggy sometimes. You might need to create a section with buttons first and then move it into the horizontal stack. 

The button card supports multiple entity types so it depends on what sensor you select on the button modal. 
You can also copy the dashboard.yaml content from the repo and paste it in your fusion config which will give you something to play around with.
