### ISSUE TITLE
Dashboard Empty after 2024.5.2

### ISSUE THREAD

**Issue by willsanderson** [matt8707/ha-fusion#476]
After updating to the latest 2024.5.2 update the dashboard is now empty with no ability to change or edit, only the sidebar is visible.

Logs below:

}
SvelteKitError: Not found: /favicon.png
    at resolve2 (file:///rootfs/build/server/index.js:4069:18)
    at resolve (file:///rootfs/build/server/index.js:3901:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3899:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:406:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1065:13)
    at send (file:///rootfs/build/server/chunks/_server.ts-BPsAyT_Z.js:18:17)
    at file:///rootfs/build/server/chunks/_server.ts-BPsAyT_Z.js:28:7
    at Session.wrapper (file:///rootfs/node_modules/youtubei.js/dist/src/utils/EventEmitterLike.js:16:17)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at Session.dispatchEvent (node:internal/event_target:742:26)
    at Session.emit (file:///rootfs/node_modules/youtubei.js/dist/src/utils/EventEmitterLike.js:11:14)
    at OAuth.<anonymous> (file:///rootfs/node_modules/youtubei.js/dist/src/core/OAuth.js:118:59)
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_STATE'
}

Node.js v20.8.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 8999
HASS_PORT: 8123
SvelteKitError: Not found: /favicon.png
    at resolve2 (file:///rootfs/build/server/index.js:4069:18)
    at resolve (file:///rootfs/build/server/index.js:3901:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3899:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 8999
HASS_PORT: 8123
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 8999
HASS_PORT: 8123

**Comment by willsanderson** [comment]
<img width="1418" alt="Screenshot 2024-05-23 at 2 04 31 PM" src="https://github.com/matt8707/ha-fusion/assets/8596886/f7949fac-a08f-40be-b1ab-b211ec2a64bf">

**Comment by matt8707** [comment]
Please post

* any browser console errors
* dashboard.yaml (or copy all yaml from "code")

![Skärmavbild 2024-05-24 kl  00 43 56](https://github.com/matt8707/ha-fusion/assets/36163594/da7f0f38-7c18-417f-a008-94fcf6b976ed)

**Comment by daywalkerb1** [comment]
> After updating to the latest 2024.5.2 update the dashboard is now empty with no ability to change or edit, only the sidebar is visible.
> 
> Logs below:
> 
> } SvelteKitError: Not found: /favicon.png at resolve2 (file:///rootfs/build/server/index.js:4069:18) at resolve (file:///rootfs/build/server/index.js:3901:34) at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26) at respond (file:///rootfs/build/server/index.js:3899:43) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { status: 404, text: 'Not Found' } node:internal/event_target:1083 process.nextTick(() => { throw err; }); ^
> 
> TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed at new NodeError (node:internal/errors:406:5) at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1065:13) at send (file:///rootfs/build/server/chunks/_server.ts-BPsAyT_Z.js:18:17) at file:///rootfs/build/server/chunks/_server.ts-BPsAyT_Z.js:28:7 at Session.wrapper (file:///rootfs/node_modules/youtubei.js/dist/src/utils/EventEmitterLike.js:16:17) at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20) at Session.dispatchEvent (node:internal/event_target:742:26) at Session.emit (file:///rootfs/node_modules/youtubei.js/dist/src/utils/EventEmitterLike.js:11:14) at OAuth. (file:///rootfs/node_modules/youtubei.js/dist/src/core/OAuth.js:118:59) at Generator.next () { code: 'ERR_INVALID_STATE' }
> 
> Node.js v20.8.1 s6-rc: info: service legacy-services: stopping s6-rc: info: service legacy-services successfully stopped s6-rc: info: service legacy-cont-init: stopping s6-rc: info: service legacy-cont-init successfully stopped s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting s6-rc: info: service legacy-services successfully started Starting Fusion... ADDON: true INGRESS_PORT: 8099 EXPOSED_PORT: 8999 HASS_PORT: 8123 SvelteKitError: Not found: /favicon.png at resolve2 (file:///rootfs/build/server/index.js:4069:18) at resolve (file:///rootfs/build/server/index.js:3901:34) at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26) at respond (file:///rootfs/build/server/index.js:3899:43) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { status: 404, text: 'Not Found' } s6-rc: info: service legacy-services: stopping s6-rc: info: service legacy-services successfully stopped s6-rc: info: service legacy-cont-init: stopping s6-rc: info: service legacy-cont-init successfully stopped s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting s6-rc: info: service legacy-services successfully started Starting Fusion... ADDON: true INGRESS_PORT: 8099 EXPOSED_PORT: 8999 HASS_PORT: 8123 s6-rc: info: service legacy-services: stopping s6-rc: info: service legacy-services successfully stopped s6-rc: info: service legacy-cont-init: stopping s6-rc: info: service legacy-cont-init successfully stopped s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting s6-rc: info: service legacy-services successfully started Starting Fusion... ADDON: true INGRESS_PORT: 8099 EXPOSED_PORT: 8999 HASS_PORT: 8123

Same here

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/476#issuecomment-2128155729

**Comment by daywalkerb1** [comment]
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 
HASS_PORT: 8123
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 
HASS_PORT: 8123
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 5020
HASS_PORT: 8123
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 5020
HASS_PORT: 8123
SvelteKitError: Not found: /auth/authorize
    at resolve2 (file:///rootfs/build/server/index.js:4069:18)
    at resolve (file:///rootfs/build/server/index.js:3901:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3899:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /auth/authorize
    at resolve2 (file:///rootfs/build/server/index.js:4069:18)
    at resolve (file:///rootfs/build/server/index.js:3901:34)
    at Object.handle (file:///rootfs/build/server/chunks/hooks.server-CE3BTx0B.js:2:26)
    at respond (file:///rootfs/build/server/index.js:3899:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}

**Comment by matt8707** [comment]
That's not the same issue https://github.com/matt8707/ha-fusion/issues/344

**Comment by Mja101** [comment]
First of all, thank you for all you have done, @matt8707!

I am facing the same issue:

![image](https://github.com/matt8707/ha-fusion/assets/30071614/dac0d454-4972-4932-87d7-13e4de9b48b2)

Console:

![image](https://github.com/matt8707/ha-fusion/assets/30071614/362eb5f0-4454-447a-b00c-4cfede2b0cc7)

**Comment by matt8707** [comment]
Please post yaml

**Comment by Mja101** [comment]
`views:
  - name: Overview
    id: 3641522019601
    sections:
      - type: horizontal-stack
        sections:
          - name: Lights
            items:
              - id: 9568023266634
                type: button
                entity_id: light.kitchen
                name: Kitchen
              - id: 4589659695625
                type: button
                entity_id: light.living_room_lights
                name: Living Room
              - id: 7450962908329
                type: button
                entity_id: light.dining_lights
                name: Dining
              - id: 1968443868175
                type: button
                entity_id: light.laundry
                name: Laundry
              - id: 6110480641737
                type: button
                entity_id: light.front_pillar_lights
                name: Front Pillars
              - id: 7610824382084
                type: button
                entity_id: light.master_lights
                name: Master Bedroom
              - id: 6084450199240
                type: button
                entity_id: light.office_lights
                name: Office
              - id: 4457172687147
                type: button
                entity_id: light.garage_lights
                name: Garage
              - id: 1985304096027
                type: button
                entity_id: light.alfresco_lights
                name: Alfresco
              - id: 1548108141204
                type: button
                entity_id: light.hallway_lights
                name: Hallway
              - id: 5908425480955
                type: button
                entity_id: light.master_lamps
                name: Master Lamps
            id: 4816034096870
          - name: Section
            items: []
            id: 8026504936879
        id: 9236087028113
      - type: horizontal-stack
        sections:
          - name: Whats Playing
            items:
              - id: 9735426291710
                type: conditional_media
                entity_id: media_player.sony_xr_75x90j
                media_players:
                  - entity_id: media_player.sony_xr_75x90j
                  - entity_id: media_player.living_room_tv
              - id: 8514794520058
                type: button
                entity_id: media_player.sony_xr_75x90j
              - id: 2637290875859
                type: button
                entity_id: light.living_room_cabinet_lights
                name: Cabinet Lights
              - id: 8148741221149
                type: conditional_media
                entity_id: media_player.symfonisk_frame
                media_players:
                  - entity_id: media_player.symfonisk_frame
              - id: 1600968581711
                type: button
                entity_id: media_player.symfonisk_frame
            id: 1387472985157
          - name: Section
            items: []
            id: 5018659218844
        id: 8721151819533
      - name: People
        items:
          - id: 9600972133407
            type: button
            entity_id: device_tracker.pixel_8_pro
            name: Michael
            icon: noto:person
          - id: 6503087167047
            type: button
            entity_id: device_tracker.marisol_s_iphone
            icon: noto:girl
            name: Marisol
        id: 215841114848
  - id: 371058918425
    type: button
    entity_id: light.bed_lamp_left
    name: Lights
sidebar:
  - id: 4015459026824
    type: template
    template: '# Welcome'
  - id: 7424080271135
    type: divider
  - id: 9120702848137
    type: time
  - id: 2714028440989
    type: date
  - id: 9955337816605
    type: weather_forecast
    entity_id: weather.forecast_home
    icon_pack: meteocons
  - id: 4980415370440
    type: divider
    mode: empty
    hide_mobile: true
  - id: 7532936211685
    type: divider
  - id: 355694269940
    type: radial
    entity_id: sensor.system_monitor_processor_use
    name: CPU
    stroke: 9
  - id: 4465945610311
    type: graph
    entity_id: sensor.system_monitor_memory_usage
    period: 5minute
    name: Memory Usage
  - id: 2337116111381
    type: bar
    entity_id: sensor.system_monitor_memory_usage
    name: RAM
  - id: 7816362227688
    type: divider
    mode: empty
    hide_mobile: true
  - id: 5801891310947
    type: divider
  - id: 1540965178917
    type: template
    template: '# There are {{ states(''sensor.lights_on'') }} lights on 💡'
  - id: 9512399735393
    type: notifications
sidebarWidth: 456
theme: muted
`

**Comment by willsanderson** [comment]
The dropdown button in the upper right corner of the dashboard doesn't currently function, so I'm unfortunately unable to paste the yaml code. 
<img width="1438" alt="Screenshot 2024-05-23 at 10 50 55 PM" src="https://github.com/matt8707/ha-fusion/assets/8596886/4bc8397c-a948-4495-b127-87280b892864">

**Comment by anarion80** [comment]
Yes, same here. Seems to be related to the conditional media, because when I remove this from the dashboard:

```yaml
          - name: Plex
            items:
              - id: 2349934717914
                type: conditional_media
                entity_id: sensor.plex_recently_added
                media_players:
                  - entity_id: media_player.nvidia_shield
                  - entity_id: media_player.chromecastaudio9331
                  - entity_id: media_player.spotify_anarion
                  - entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
                timeout: 10
                show_timeout: true
                marquee: true
            id: 5684458028364
```
then it works again.

With that, I get the following on the console:

```javascript
Empty.BqSgeKo3.js:2 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'media_player.nvidia_shield')
    at Empty.BqSgeKo3.js:2:47421
    at Array.map (<anonymous>)
    at fe (Empty.BqSgeKo3.js:2:47397)
    at l.$$.update (Empty.BqSgeKo3.js:2:50162)
    at jt (index.DcjOQeC1.js:4:3914)
    at new qi (Empty.BqSgeKo3.js:2:50917)
    at Array.wt (Index.CWlElIbp.js:2:3199)
    at Et (Index.CWlElIbp.js:2:4432)
    at jt (index.DcjOQeC1.js:4:3960)
    at new Ye (Index.CWlElIbp.js:2:5120)
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'parentNode')
    at w (scheduler.B6-qTMgR.js:1:3582)
    at Object.d (Icon.DSnr4b0n.js:1:1365)
    at $t (index.DcjOQeC1.js:4:3266)
    at Object.d (Empty.BqSgeKo3.js:2:3518)
    at index.DcjOQeC1.js:4:911
    at z (scheduler.B6-qTMgR.js:1:366)
    at Array.forEach (<anonymous>)
    at I (scheduler.B6-qTMgR.js:1:427)
    at xt (index.DcjOQeC1.js:4:757)
    at store.C1XxddWe.js:1:475
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at P (scheduler.B6-qTMgR.js:1:4200)
    at St (scheduler.B6-qTMgR.js:1:4545)
    at Object.p (Icon.DSnr4b0n.js:1:1107)
    at Object.p (Icon.DSnr4b0n.js:1:478)
    at Object.p (Icon.DSnr4b0n.js:1:1287)
    at lt (scheduler.B6-qTMgR.js:1:8787)
    at ct (scheduler.B6-qTMgR.js:1:8440)
2
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'parentNode')
    at w (scheduler.B6-qTMgR.js:1:3582)
    at Object.d (Icon.DSnr4b0n.js:1:1365)
    at $t (index.DcjOQeC1.js:4:3266)
    at Object.d (Empty.BqSgeKo3.js:2:3518)
    at index.DcjOQeC1.js:4:911
    at z (scheduler.B6-qTMgR.js:1:366)
    at Array.forEach (<anonymous>)
    at I (scheduler.B6-qTMgR.js:1:427)
    at xt (index.DcjOQeC1.js:4:757)
    at store.C1XxddWe.js:1:475
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at P (scheduler.B6-qTMgR.js:1:4200)
    at St (scheduler.B6-qTMgR.js:1:4545)
    at Object.p (Icon.DSnr4b0n.js:1:1107)
    at Object.p (Icon.DSnr4b0n.js:1:478)
    at Object.p (Icon.DSnr4b0n.js:1:1287)
    at lt (scheduler.B6-qTMgR.js:1:8787)
    at ct (scheduler.B6-qTMgR.js:1:8440)
    at n (store.C1XxddWe.js:1:577)
    at store.C1XxddWe.js:1:621
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at P (scheduler.B6-qTMgR.js:1:4200)
    at Object.p (Empty.BqSgeKo3.js:2:10258)
    at lt (scheduler.B6-qTMgR.js:1:8787)
    at ct (scheduler.B6-qTMgR.js:1:8440)
scheduler.B6-qTMgR.js:1 
 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at P (scheduler.B6-qTMgR.js:1:4200)
    at Object.p (Empty.BqSgeKo3.js:2:10258)
    at lt (scheduler.B6-qTMgR.js:1:8787)
    at ct (scheduler.B6-qTMgR.js:1:8440)
    at n (store.C1XxddWe.js:1:577)
    at store.C1XxddWe.js:1:621
```
