### ISSUE TITLE
Conditional Display for Dashboard Entities

### ISSUE THREAD

**Issue by cd1zz** [matt8707/ha-fusion#490]
@matt8707 have you considered adding conditional cards as an option for the dashboard? For example, if I display my door/window sensors from the alarm panel, it will fill up an entire screen. However, all I really care about is the ones that are open. For reference:  https://www.home-assistant.io/dashboards/conditional/

Appreciate the development on this dashboard, it's the best one out there!

**Comment by matt8707** [comment]
Hi, yes discussed here https://github.com/matt8707/ha-fusion/issues/63
