### ISSUE TITLE
translation German - state missing

### ISSUE THREAD

**Issue by snopy81** [matt8707/ha-fusion#5]
Hi,
just figured out that state is still showing in English for entities like cover.xxx if UI is set to German.

proposed translation:
English = German
Open = Geöffnet
Closed = Geschlossen

Are further states like 'closing' will be displayed?
![grafik](https://github.com/matt8707/ha-fusion/assets/45458092/0841aeaa-262e-4862-b3df-c8a93131fa9b)

**Comment by dierochade** [comment]
I do not know if localisation is top priority right now? 

Maybe it is possible to reference the work done in ha to get a congruent experience, without any effort?

besides I am a native speaker of German and would love to take part in this project. Just pm me.

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/releases/tag/2023.12.4
