### ISSUE TITLE
Ability to run Input_boolean from a button

### ISSUE THREAD

**Issue by notorioustubze** [matt8707/ha-fusion#50]
Thank you for the amazing work thus far!
It would be really cool if we could run input_boolean's via a button press.

**Comment by joe-heaton** [comment]
Pressing in the highlighted area will toggle input_booleans on/off, it's a workaround for now until the entire button is configured.

![CleanShot 2024-01-01 at 19 15 47@2x](https://github.com/matt8707/ha-fusion/assets/93256786/b09d51ab-d2d1-4e32-a6ee-190922243949)
