### ISSUE TITLE
Why does the sidebar have so many options that are not in the main part like templates bars etc.

### ISSUE THREAD

**Issue by ItsCharged** [matt8707/ha-fusion#509]
read title. AND PLEASE DO NOT MARK THIS AS DUPLICATE!!! I did not find the "duplicate" of this comment please tell me why.

**Comment by matt8707** [comment]
Hi, did you read this?

> The current state of this project is pre-beta. This means that there's basic functionality missing, incomplete features and unresolved issues. General feedback, bug reports and feature requests are welcome!

**Comment by ItsCharged** [comment]
> Hi, did you read this?
> 
> > The current state of this project is pre-beta. This means that there's basic functionality missing, incomplete features and unresolved issues. General feedback, bug reports and feature requests are welcome!

Yes i did, but thats the question I just wanted to ask if there is a specific reason

**Comment by ItsCharged** [comment]
Imam openfeature request
