### ISSUE TITLE
Maptiler Map doesn't show up

### ISSUE THREAD

**Issue by svherrma** [matt8707/ha-fusion#536]
Hi @matt8707 ,
first big thanks for this great project. loving it 👍 

i tried to get map working as written in the [Map.md](static/documentation/Map.md).

but nothing is showing up, when clicking on one person tile.

am i missing something? or is it limitated to some special regions?

best regards
sven

**Comment by matt8707** [comment]
https://github.com/matt8707/ha-fusion/issues/310

**Comment by svherrma** [comment]
omg.. sorry @matt8707 overseen this closed issue. now it works as expected. thanks 🚀
