### ISSUE TITLE
Door and motion sensors showing on/off states

### ISSUE THREAD

**Issue by paulmorabito** [matt8707/ha-fusion#548]
Is it possible to change the defaults for door sensors to be open/closed and for motion to be "Detected/Clear" or something along these lines?

**Comment by benepixx** [comment]
Yes, Just Paste this into the state template editor and you're all good: Its labelled state and there's a button that looks like this {}

Obviously edit for open/close.

{% if is_state(entity_id, "on") %}
  Detected
{% else %}
  Clear
{% endif %}
