### ISSUE TITLE
FR: Option to disable button modal

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#56]
Ik you push a button not on the round area a yaml pop up appears.
I like the possability to hit the button everywhere to start the action:
![image](https://github.com/matt8707/ha-fusion/assets/23150947/314ac4fa-57b0-43bf-95ce-65da170bef8d)

**Comment by matt8707** [comment]
related https://github.com/matt8707/ha-fusion/issues/44

This would have to be an option to disable popup

**Comment by xrolfex** [comment]
This should now be resolved.
