### ISSUE TITLE
How to use HA-Fusion as homepage?

### ISSUE THREAD

**Issue by SkyLostTR** [matt8707/ha-fusion#565]
Greetings,

I would like to set the HA-Fusion dashboard as the default homepage that appears when I open Home Assistant. Could you please guide me on how to configure this?

Thank you

**Comment by TheOpsMgr** [comment]
Duplicate of https://github.com/matt8707/ha-fusion/issues/558 ?

**Comment by SkyLostTR** [comment]
Tried to search it first but didn't see that one, closing this one.

**Comment by Sundancer78** [comment]
Go to the configuration of the HA-Fusion add-on, enable/change the port, save the configuration. Restart the add-on. In the web browser, enter the port you entered in the configuration instead of port 8123 after the address of your Home Assistant.

**Comment by Sundancer78** [comment]
Go to the configuration of the HA-Fusion add-on, enable/change the port, save the configuration. Restart the add-on. In the web browser, enter the port you entered in the configuration instead of port 8123 after the address of your Home Assistant.
