### ISSUE TITLE
FR: Device battery

### ISSUE THREAD

**Issue by Donkie** [matt8707/ha-fusion#59]
Would like to start off with saying I really love this UI!

I am running it on an dedicated Android tablet. It would be nice to be able to see the tablet's battery level in the UI. Something that could be achieved by creating a dedicated card that interacts with the https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API .

What do you think?

**Comment by matt8707** [comment]
No, the browser support is too limited. However, there are alternative methods to achieve this, such as using the Fully Kiosk app and integrating its sensors with HA

**Comment by Donkie** [comment]
Oh, that's a great alternate solution, I will investigate, thank you!
