### ISSUE TITLE
New climate view is changing to heating while openig the button

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#60]
The new climate button is automaticly changing to heating when opening, even if the state was automate.
I do expect that it keeps its originall state until after changing

It will also be nice showing the actuall temperature beside the setting temperature. Now I do need to create 2 devices

![image](https://github.com/matt8707/ha-fusion/assets/23150947/9f4a4012-437d-4708-8df0-ff49cb7dff87)

Something like:
![image](https://github.com/matt8707/ha-fusion/assets/23150947/fb87cfb9-bcdb-43a4-a075-7a3575229cca)
would be very nice

**Comment by matt8707** [comment]
Did 2024.1.1 fix this?

**Comment by canedje** [comment]
Yes. Thanks very much
