### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by civic-sir** [matt8707/ha-fusion#602]
I'm trying to add Fusion as the only dashboard that my guest account can see. 
Given that Fusion is not really a dashboard that I can edit the code to add 

kiosk_mode:
  non_admin_settings:
    kiosk: true
    ignore_entity_settings: true

On its raw configuration for dashboard. Is there a way to get this working for this one? 

I tried to add it to fusions raw code Editor but that didn't work either. 

Any help would be greatly appreciated. 

Thanks a lot

**Comment by xitters** [comment]
Go to fussion addon, settings , and configure an access port 
![imagen](https://github.com/user-attachments/assets/536cbd04-bb62-41a4-9718-c77bf0350e80)

Then if you go to your HA ip http://192.xx.xx.xxx:8099?menu=false
And put Dashboard with URL. I think

**Comment by xitters** [comment]
Or try http://192.xx.xx.xxx:8099?kiosk

**Comment by civic-sir** [comment]
That didn't quiet work. 
I have to use 
http://192.xx.xx.xxx:8099/XXX_ha_fusion/ingress?kiosk  -- Even ?menu=false doesn't work :(

Otherwise putting 
http://192.xx.xx.xxx:8099/?kiosk
will just direct me to the default dashboard. Right now i have blank. Not the fusion dashboard.

**Comment by xitters** [comment]
First of all, try the HA IP address http://192.xx.xx.xxx:8099
only with the port that you configured in fusion, it should send you to the fusion page
![Sin título](https://github.com/user-attachments/assets/68745d23-bf4d-4b26-8133-d72dc3299a67)

**Comment by xitters** [comment]
This is how I cast the fusion page to a nest hub
[http://192.xx.xx.xxx:8099?menu=false](http://192.xx.xx.xxx:8099/?menu=false)
![20241127_174353](https://github.com/user-attachments/assets/19481c07-9d02-4964-931f-d7571b9c0f25)

**Comment by civic-sir** [comment]
Oh that is SWEET! Thats exactly what i want, and you got the menu at the top disappeared. 
Right now i have my HA through cloudflare tunnel. 

It's at my second home property 5000miles away. 
Let me see if i can configure cloudflare with the url you provided. so that www.homeassistantaddress.com goes to the page you have. 
Thanks!

**Comment by civic-sir** [comment]
OMG You are a genius! That worked but small problem.

![Screenshot 2024-11-27 at 2 02 09 PM](https://github.com/user-attachments/assets/36f64c91-a36c-48b6-83f8-23f5f8a75d5a)

All of the icons and graph are missing :( 


Second question: How did you remove the DOWN arrow on top right
![Screenshot 2024-11-27 at 2 03 17 PM](https://github.com/user-attachments/assets/c72a1133-0e56-494b-86ef-2cafcdf6b458)

**Comment by xitters** [comment]
to cast you need https://github.com/AlexxIT/DashCast integration and make and automation like this:

```python
alias: DashCast Nest HUB HA
description: ""
triggers:
  - entity_id: media_player.nesthubea23
    to: "off"
    for:
      minutes: 1
    trigger: state
  - entity_id: media_player.nesthubea23
    to: paused
    for:
      minutes: 1
    trigger: state
  - entity_id: media_player.nesthubea23
    to: idle
    for:
      minutes: 1
    trigger: state
conditions:
  - condition: state
    entity_id: binary_sensor.192_xxx_xx_xxx
    state: "on"
actions:
  - data:
      force: true
      reload_seconds: 0
      entity_id: media_player.nesthubea23
      url: http://192.xxx.xx.xxx:8099?menu=false
    action: dash_cast.load_url
mode: single

```

**Comment by xitters** [comment]
> OMG You are a genius! That worked but small problem.
> 
> ![Screenshot 2024-11-27 at 2 02 09 PM](https://private-user-images.githubusercontent.com/59845349/390576839-36f64c91-a36c-48b6-83f8-23f5f8a75d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDU3NzksIm5iZiI6MTczMjc0NTQ3OSwicGF0aCI6Ii81OTg0NTM0OS8zOTA1NzY4MzktMzZmNjRjOTEtYTM2Yy00OGI2LTgzZjgtMjNmNWY4YTc1ZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIyMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjdmZTIwYjkwZTg5MGY4OWQzOGE0ZmQwNGY4MjA1ODM4NjA1YjZiNzhkYmQ5MzUwMTdkOGQxMTdiZDBlMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nJnPkhX-wgvSRP9P1YYW-IFq20iD4kTWOQ6Ty-g7DKo)
> 
> All of the icons and graph are missing :(
> 
> Second question: How did you remove the DOWN arrow on top right ![Screenshot 2024-11-27 at 2 03 17 PM](https://private-user-images.githubusercontent.com/59845349/390577060-c72a1133-0e56-494b-86ef-2cafcdf6b458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDU3NzksIm5iZiI6MTczMjc0NTQ3OSwicGF0aCI6Ii81OTg0NTM0OS8zOTA1NzcwNjAtYzcyYTExMzMtMGU1Ni00OTRiLTg2ZWYtMmNhZmNkZjZiNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIyMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjIzZjFkZjA1MGJjZDk2ODA1ODcyOGZmYWI2MTRiYzkwMTFkNjEyZmFlM2MzNmNhZTVhYWNmYjBhNTMwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bi2OIp67j81Q5G3Y0KrpGls9BeajplZ4G4etgIDCmWA)

I dont know, internet conection problems? or you need to refresh, in my cast no have any of this problems.

The arrow hide with ?menu=false

**Comment by xitters** [comment]
clear browser cache? Ctrl+F5

**Comment by civic-sir** [comment]
Ah i see. 
Right now my Home Assistant is on a wall mount tablet at the property. 

I think the reason the script / icons / graphs don't works is because i'm running this through my CloudFlare tunneling (remote connection). I will try this out when i'm at the property and local network. 
Thanks soooo much! This was helpful.

**Comment by xitters** [comment]
You can try how the cast looks with this

https://stestagg.github.io/dashcast/

Force display? put yes

**Comment by civic-sir** [comment]
The only downside with this template is that it does not allow for temperature control. 
Right now i have a thermostat and can't create an object that has 

[+] CURRENT TEMP [-] 

OR even those dials slider as seen below.

![Screenshot 2024-11-27 at 2 22 00 PM](https://github.com/user-attachments/assets/5bd1c6e3-5623-453e-8302-41f33813d861)

**Comment by xitters** [comment]
> The only downside with this template is that it does not allow for temperature control. Right now i have a thermostat and can't create an object that has
> 
> [+] CURRENT TEMP [-]
> 
> OR even those dials slider as seen below.
> 
> ![Screenshot 2024-11-27 at 2 22 00 PM](https://private-user-images.githubusercontent.com/59845349/390580677-5bd1c6e3-5623-453e-8302-41f33813d861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDY0NjUsIm5iZiI6MTczMjc0NjE2NSwicGF0aCI6Ii81OTg0NTM0OS8zOTA1ODA2NzctNWJkMWM2ZTMtNTYyMy00NTNlLTgzMDItNDFmMzM4MTNkODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIyMjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWYyZjYyMjQ1ZjFhZTZmNDllN2JhMWIwYzVkNDIxMDRhMTQzOWQ4NDM1N2I0Yzk3ZDc3MDA1OGE0ZjRhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7BCy2lGapP1_znJsO21RqMqhKX3Q-_siS0KZF54qJd8)

I don't know about that, I'm just a simple fusion user. But what I can tell you is that it is in beta phase, the basics work.
I use it because of how it looks on googlenesthub2 and because the interface loads faster on it.

**Comment by civic-sir** [comment]
Oh no problem! Yeah wasn't sure if they solved this one.
Thanks sooo much for everything I'll go ahead and close this ticket.

**Comment by xitters** [comment]
here you have more information:
https://community.home-assistant.io/t/ha-fusion-a-modern-easy-to-use-and-performant-custom-home-assistant-dashboard/662071/123
