### ISSUE TITLE
camera is not accepting unifi doorbell and crashing the page

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#61]
If I add my Unifi doorbell as camera it will not be accepted.
Not showing the camera
Saving is not possible
Page is crashing

I think it is something to do with picture length and with sizes.
My other Unifi camer is working fine. These having a different picture format size

**Comment by xrolfex** [comment]
Is this the G4 or Pro?
Are you exposing through RTSP streams in HA, what quality do you have enabled?

**Comment by canedje** [comment]
No I'm using the protect integration to use the Unifi cams.
All other 3 cams are working fine

**Comment by canedje** [comment]
EDIT: I found out it has nothing to do with the camera type or sizes.
Its not possible to add more then 3 camera's at a page.
Camera 4 is not accepted

**Comment by mape** [comment]
When testing for https://github.com/matt8707/ha-fusion/pull/108 I noticed having multiple cameras caused loading issues.

After changing so the dev server was served using HTTPS/H2 the issue went away.

Could this be related to max concurrent connections per domain?

**Comment by canedje** [comment]
UPDATE:
I tried today again to add my 7 camera's as a separate page in HA-Fusion.
I'm now able to do, but makes HA-Fusion unusable because it makes it terrible slow and not workable
