### ISSUE TITLE
Ipad View Bug

### ISSUE THREAD

**Issue by Harti33** [matt8707/ha-fusion#62]
When you scroll between the different Views on the Ipad, it opens the Keyboard on every View. Smething gets marked as you can see at the Blue Line on the Top.

![6CB73CB0-516E-44A8-AACD-6680583CC013](https://github.com/matt8707/ha-fusion/assets/97918385/523f9669-29a9-41dc-a173-37fd5f789d93)

**Comment by janiskelemen** [comment]
I can take a look at it when I do the mobile support in #15
