### ISSUE TITLE
FR: Component visibility control

### ISSUE THREAD

**Issue by taylorfinnell** [matt8707/ha-fusion#63]
Thanks so much for making this project, it's awesome!

I would like to request a feature that allows visibility logic for components. 

Example usecase:
 - Only showing a camera feed when a motion binary sensor is on

Is this something that you could see fitting into this project? I would be happy to take a stab at it. I imagine a checkbox on the component's configuration page named something like `Visible when`. When checked the user can pick various binary_sensors. Possibly combining multiple into an expression, eg: `binary_sensor.outdoor_motion and binary_sensor.is_dark`. I think section visibility should be controllable too

Thanks!

**Comment by maddox** [comment]
It seems that this could be best implemented with a Visibility Template field. Then we can use the existing templating support to just let it return true/false.

**Comment by matt8707** [comment]
I think it should be a new "card", something like [conditional card](https://www.home-assistant.io/dashboards/conditional/), but yes with template

**Comment by jaburges** [comment]
this would also go hand in hand with the chips / header request.
If there is motion show a motion icon with a badge number.
if there is a door open (or unlocked) show an icon with a badge number.

**Comment by t0bse** [comment]
i use auto entities for window sensors. the card is not visible, if no windows are open
type: custom:auto-entities
card:
  type: entities
  title: Fenster
filter:
  include:
    - domain: binary_sensor
      entity_id: '*contact*'
      state: 'on'
      options: {}
show_empty: false

![image](https://github.com/matt8707/ha-fusion/assets/45834518/3d2ea122-addd-4b49-bddd-451af7db6f94)

![image](https://github.com/matt8707/ha-fusion/assets/45834518/cf1e65d6-c45b-493f-9829-a1d1ad8f9eae)
