### ISSUE TITLE
Light button missing controls for on/off

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#65]
Running 2024.1 as an addon

I have multiple "dumb" lights that do not have any brightness adjustment, they are just on/off switches. While these can be turned on/off using the Icon in the dashboard, they have no controls visible when you open the properties, making it impossible to control them individually when they are part of a group:

![image](https://github.com/matt8707/ha-fusion/assets/73796046/c6a93ad8-2331-461f-9806-7679aea59c66)

Even for lights that do have a brightness slider, a simple on/off toggle would make it easier to control them without having to drag the slider to 0% to switch them off:

![image](https://github.com/matt8707/ha-fusion/assets/73796046/1fa24659-ad34-41ba-9de0-cc08cf5513c5)

Thanks!

**Comment by Plawasan** [comment]
See below - they are in most cases switches dressed up as lights using the "Switch as X" helper:

```
supported_color_modes: onoff
color_mode: null
icon: mdi:wall-sconce-flat-outline
friendly_name: Office Light
supported_features: 0
```

**Comment by matt8707** [comment]
So they are `switch.abc` entities?

**Comment by Plawasan** [comment]
No, they are `light.xxx`

You can set one up in HA from any switch using the "Show as" attribute - it hides the original `switch.xxx` and creates a `light.xxx`

![image](https://github.com/matt8707/ha-fusion/assets/73796046/7d7fed93-98eb-4d0e-add1-72d9e7e0016e)

This is my Shelly controlling the 2 lights with both the switches and the lights:

![image](https://github.com/matt8707/ha-fusion/assets/73796046/8e5bbadf-97c4-4669-bfd2-abceca66e7e3)

**Comment by matt8707** [comment]
Thanks!
