### ISSUE TITLE
FR: Set entity name in sidebar (graph)

### ISSUE THREAD

**Issue by Lancealot1990** [matt8707/ha-fusion#68]
Sometimes Sensors can have a long entity name, being able to change the name shown would be great to have so were able to shorten it so whatever we want it to show :)

For example : my sensor is : "sensor.givtcp_xxxxxxx_grid_to_house"  but want it to show just "Grid To House"

thanks again

**Comment by canedje** [comment]
I think thats already possible? Or amI wrong?
![image](https://github.com/matt8707/ha-fusion/assets/23150947/29abc612-732a-4edf-8b1f-61484a9e87f8)

**Comment by Lancealot1990** [comment]
You can do it to other things such as buttons but not for the graph sensor in the side bar. 
![image](https://github.com/matt8707/ha-fusion/assets/118307358/2e19a3ff-4ffd-41a8-bbf0-bf200d6310ee)

**Comment by MondayMorning-sys** [comment]
Did you try setting a friendly name to the sensor? It might helps with the issue.

**Comment by Lancealot1990** [comment]
I will certainly give this a try and report back!

Thanks  all

**Comment by Lancealot1990** [comment]
I can confirm that does do the trick and resolves that issue, however would
still be good to be able to change the name within fusion for easiness.

Thanks again for the simple tip.
