### ISSUE TITLE
Page not loading and unable to edit

### ISSUE THREAD

**Issue by notorioustubze** [matt8707/ha-fusion#7]
First of all thank you for your hard work once I have this set up and working as intended I'm sure it's going to be fantastic.

So the issues I'm facing:

Firstly, I can only get the display to show when using the home assistant application. If I try in the web browser I just get a black screen. (Unsure if web page hasn't been implemented yet if not my bad) 

The other issue I have when I'm using the HA app and I get to the welcome screen and every time I click edit on side bar I just get a white spinning circle and nothing happens. Picture attached.

Thanks again!

<img width="1786" alt="Screenshot 2023-12-26 at 11 37 19" src="https://github.com/matt8707/ha-fusion/assets/53260708/042f3770-dbfb-4c7f-809c-e7640c165785">

**Comment by matt8707** [comment]
Please update and rebuild

![screen](https://github.com/matt8707/ha-fusion/assets/36163594/a521dc63-a375-4c7e-9b9b-4270657bc70f)

If it still freezes post any browser console errors

**Comment by notorioustubze** [comment]
Hi, Thank you for the prompt response I'd updated but failed to click the rebuild button. All working now and WOW! This really is incredible.
