### ISSUE TITLE
Configure as default dashboard

### ISSUE THREAD

**Issue by wouterrutgers** [matt8707/ha-fusion#71]
Hi there! I'm wondering if there are any configuration tricks that can be done to make this dashboard the default one in HA.

Currently, the default HA dashboard pops up because I've deleted my other dashboards, but I'm not sure if there's a way to change that. Is this something that can't be done, as I can't select it as the default dasbhoard, or are there some hidden ways to do it? Thank you so much!

**Comment by matt8707** [comment]
There's not, this is not technically a ha dashboard, just an addon.

**Comment by imMrRAW** [comment]
> Hi there! I'm wondering if there are any configuration tricks that can be done to make this dashboard the default one in HA.
> 
> Currently, the default HA dashboard pops up because I've deleted my other dashboards, but I'm not sure if there's a way to change that. Is this something that can't be done, as I can't select it as the default dasbhoard, or are there some hidden ways to do it? Thank you so much!

https://github.com/matt8707/ha-fusion/issues/228#issuecomment-1902672896
