### ISSUE TITLE
Question: Matter-fusion

### ISSUE THREAD

**Issue by StuartIanNaylor** [matt8707/ha-fusion#73]
Would you have any plans on providing a dashboard that can work with https://github.com/project-chip/matter.js ?

**Comment by matt8707** [comment]
I have a question as well. What do you mean?

**Comment by StuartIanNaylor** [comment]
I was just curious about Matter and how it performs native. https://github.com/project-chip/matter.js?tab=readme-ov-file#monorepo-code-structure-overview seems to have all the building blocks for native Matter but is just missing a dashboard module, from what I can see.
I was impressed with what you have done with ha-fusion and it being .js and the project-chip also being .js as likely just just native Matter you can commision using the CLI, but a dashboard would be nice.

**Comment by matt8707** [comment]
Ah okay, it is beyond the scope of this project!
