### ISSUE TITLE
Non-16:9 Aspect Ratio Cameras Not Handled

### ISSUE THREAD

**Issue by zimmra** [matt8707/ha-fusion#74]
Appears like all camera objects 'want' to be 16:9

I have a 4:3 and 8:3 camera and neither are formatted correctly in the card view. In the pop-up/modal view they are formatted correctly

![image](https://github.com/matt8707/ha-fusion/assets/28514085/41197bcc-94bf-4b54-8ee2-553ad84b27db)

**Comment by Donkie** [comment]
I have the same issue, but with a 16:9 camera:
![image](https://github.com/matt8707/ha-fusion/assets/2332094/e260d499-d37b-4001-a375-2b728cba37f2)
Works fine in the modal preview though:
![image](https://github.com/matt8707/ha-fusion/assets/2332094/f78c362c-011d-487f-9e96-c73967c5311f)

The area outside the scrollbars consist of a camera still image (black in the screenshot here), while inside the scrollbars is the live feed

Resolution 1024x576
It's a MJPEG IP camera

**Comment by mape** [comment]
This should hopefully be fixed by https://github.com/matt8707/ha-fusion/pull/108 and https://github.com/matt8707/ha-fusion/pull/109
