### ISSUE TITLE
Running HA-Fusion as docker under Unraid consuming Docker allocation

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#79]
The HA-Fusion is consuming Docker Allocation going up constantly.
I do run HA-Fusion as a docker under Unraid
Within a day it is growing from 37% to 79% and going on.
It looks like a kind of dataleak.
I stopped the container and the docker location immediatly returned to 37%
![image](https://github.com/matt8707/ha-fusion/assets/23150947/c5dcf685-8290-4571-ac3f-093f6c036fe4)

**Comment by matt8707** [comment]
Are you using cameras by any chance?

**Comment by canedje** [comment]
Yes I am

**Comment by matt8707** [comment]
Can you remove them and see if it still happens after some time?

**Comment by canedje** [comment]
I will do

**Comment by canedje** [comment]
After 4 Hrs the docker allocation is not growing and still 37% as it was in the beginning.
It looks like indeed that's something to do with camera's

**Comment by canedje** [comment]
I did add 2 camera's to the sidebar again. No increase of docker allocation so far:
![image](https://github.com/matt8707/ha-fusion/assets/23150947/0cafa1be-ad0b-4cad-8795-47fde4454992)
![image](https://github.com/matt8707/ha-fusion/assets/23150947/a3b37576-41ff-4801-a974-e36f90864bd9)
