### ISSUE TITLE
Camera view not working, URL points to incorrect IP (192.168.1.241)

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#8]
Running Fusion as addon, currently on 2023.12.4.

When I add a camera view, I don't actually an image - when I inspect the DOM, I see the object URL points to an incorrect IP (192.168.1.241, while my instance is running at 192.168.1.10)

` background-image: url("http://192.168.1.241:8123/api/camera_proxy/camera.garage_camera?token=xxx")`

I noticed the same IP pop up when I opened the fusion web from mobile... possibly a forgotten hardcoded IP in the source code? I assume this is you DEV IP :)

https://github.com/search?q=repo%3Amatt8707%2Fha-fusion%20%20192.168.1.241&type=code

**Comment by matt8707** [comment]
Try to reinstall to pull latest commit https://github.com/matt8707/ha-fusion/commit/49c7ea12e6cf7c12ba5c7c43aa77b3908b76bad5

**Comment by Plawasan** [comment]
Camera works now but still getting an error when I open the dashboard from mobile:

![Screenshot_20231226_170726_Home Assistant.jpg](https://github.com/matt8707/ha-fusion/assets/73796046/d7111d67-2fd9-4713-8ae9-9d77cadbb093)

**Comment by paparapapapapa** [comment]
I get the same but straight on the "home" (ingress), both on Firefox and Safari (both updated). 
It only kinda works on Chrome but it gets stuck when trying to configure buttons.
No errors on logs.

HA
    Core 2023.12.3
    Supervisor 2023.12.0
    Operating System 11.2
    Frontend 20231208.2
Fusion
    Current version: 2023.12.5

<img width="1447" alt="Screenshot 2023-12-27 alle 10 51 33" src="https://github.com/matt8707/ha-fusion/assets/56885560/ffccb93f-334d-407e-ab4c-1be960ab1ffc">

**Comment by matt8707** [comment]
Can you clear cache and write the steps on how to replicate getting 192.168.1.241?

**Comment by Plawasan** [comment]
> Can you clear cache and write the steps on how to replicate getting 192.168.1.241?

In my case it's just opening the fusion web from the app..

https://imgur.com/a/3tuCNS7

I'm also having an issue on my tablet (running under a different account than my primary user), there the frontend opens, loads the layout with all buttons etc however there are all Unknown and I get a "ERR_CANNOT_CONNECT" message. If that's a separate issue, I will create an entry for it.

**Comment by paparapapapapa** [comment]
> In my case it's just opening the fusion web from the app..

Same for me. I did nothing but:
1. Installing the add on
2. Opening the ingress address by clicking on the side bar in Firefox 
3. Repeating point 2 also in Safari and Chrome
4. When I saw the dashboard working in Chrome I tried to add a button and didn’t work.

**Comment by matt8707** [comment]
Please try addon 2023.12.6

**Comment by Plawasan** [comment]
Progress...? I no longer get the auth error but I'm getting the connection error now on mobile (same user as PC) and tablet (different user) while it works ok from my PC.

https://imgur.com/a/8dcAP6V

**Comment by matt8707** [comment]
omg i published the addon before pushing the fix, sorry please try 2023.12.7 when it's available

**Comment by Plawasan** [comment]
> omg i published the addon before pushing the fix, sorry please try 2023.12.7 when it's available

Is it meant to take me to the HA login page now? Because that's what it does...

**Comment by paparapapapapa** [comment]
OK great now it seems to work I'm going to test it next week

**Comment by matt8707** [comment]
> Is it meant to take me to the HA login page now? Because that's what it does...

Yeah, it's not ideal but at least no errors

https://developers.home-assistant.io/docs/add-ons/presentation?_highlight=ingress#ingress

> Users are previously authenticated via Home Assistant. Authentication is not required

Sounds good, but there are zero examples of it anywhere..
