### ISSUE TITLE
Hvac 2024.1.1

### ISSUE THREAD

**Issue by Holewijn** [matt8707/ha-fusion#85]
I’ve just updated to latest version. Hvac is still not good. Heating gives me now in main screen undefined see screenshot 
![IMG_1650](https://github.com/matt8707/ha-fusion/assets/16470505/2f1d5eea-b457-42c5-8f4b-73a23e2eae50)
![IMG_1651](https://github.com/matt8707/ha-fusion/assets/16470505/e6676f87-fc98-4a69-813a-734ddb28edba)

**Comment by matt8707** [comment]
duplicate #22
