### ISSUE TITLE
Show_details_on_interaction not remembering actual state

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#88]
I apologize for the lot of issues I post.
I still love these application, it is something I did waiting for for a long time.
The most positive items for me are that its very easy to configure and the use is very fast reacting.
So thank you very much for this application!!!!!

every time you open a sensor edit screen the Show_details_on_interaction it shows an activated situationand not remembering actual state
![image](https://github.com/matt8707/ha-fusion/assets/23150947/9aecab36-0be6-4fe1-9f94-dc1b461fade1)

**Comment by xrolfex** [comment]
Is this sensor in the sidebar or the main grid of buttons?

**Comment by xrolfex** [comment]
This should be resolved now.

**Comment by canedje** [comment]
Yes it is. Thanks
