### ISSUE TITLE
FR: Zoom factor

### ISSUE THREAD

**Issue by Plawasan** [matt8707/ha-fusion#91]
Right now when I display the Fusion dashboard on my tablet (2560 x 1600, 11") I end up with rather large UI elements but not a lot of them (compared to viewing the same dashboard on an ultra-wide monitor). Would be great to have the possibility to set a zoom/view ratio, ideally per device/screen size...

**Comment by matt8707** [comment]
This is something you should set in your browser

**Comment by Plawasan** [comment]
How would I do that within the HA app? Genuinely interested..

**Comment by matt8707** [comment]
under general

macOS

![macos_](https://github.com/matt8707/ha-fusion/assets/36163594/82d78296-5d69-4cda-a03c-9b7e4529e82e)


ios

![ios](https://github.com/matt8707/ha-fusion/assets/36163594/7e344f68-4bdc-421b-b9fc-6cfd9e61459f)

**Comment by Plawasan** [comment]
It's an Android tablet running the HA Companion app, I can enable pinch to zoom within the HA app but that only allows me to zoom in, not out..

**Comment by matt8707** [comment]
Okay, then you can open an issue here https://github.com/home-assistant/android

**Comment by nagtegaal** [comment]
Shouldn’t the question need to be:
Can we alter/change the default “theme” and “font options”? With other words, can we override/change the default look of the used theme -  and if so - how this could be achieved? Or is this another request?
It seems these 2 options, are quite related to each other…

**Comment by matt8707** [comment]
Yes, support for themes is planned
