### ISSUE TITLE
HVAC 

### ISSUE THREAD

**Issue by Lancealot1990** [matt8707/ha-fusion#93]
I think this has already been covered in thread #22.

I have added the HVAC card to Fusion and have tested it and it controls perfectly, however one thing that would be good is to show the state in colour, so if it a standard colour you know the heating isn't and in idle state, and if its on it goes to an amber colour. 

Same goes for the hot water, it shows hotwater on but no state colour.

As you can see, the state says it heating but no colour to indicate it. 
![image](https://github.com/matt8707/ha-fusion/assets/118307358/64ddd024-e861-406d-83cb-891e78412615)

is this something that can be implemented going forward ?

thanks again

**Comment by canedje** [comment]
Yes and the actual temperature if possible

**Comment by xADDRx** [comment]
> Yes and the actual temperature if possible

Is it possible to add the current temperature? It would be nice if you could select an additional sensor for a separate sensor.

and would it be possible to mark it red, for example, when the heating is active. You can hardly see whether the heating is on or off... :)

![grafik](https://github.com/matt8707/ha-fusion/assets/64784940/13998642-d508-4244-9ba2-e5d8b0ebeb6b)

**Comment by matt8707** [comment]
@xADDRx please create a new issue, this one is closed
