### ISSUE TITLE
Person entity images not showing correctly

### ISSUE THREAD

**Issue by maddox** [matt8707/ha-fusion#95]
I'm not seeing images for Person entities. I've uploaded avatars via Home Assistant's Person settings by choosing the hass user and uploading the avatar.

<img width="258" alt="image" src="https://github.com/matt8707/ha-fusion/assets/260/18628ae7-d37c-488e-94b5-7e9f3704cebf">

**Comment by Holewijn** [comment]
Clear cache, i don't have that problem here.

**Comment by maddox** [comment]
It's not cache, as I've set up a local development version and the issue happens there too.

The image request on ha-fusion is getting a 404:

```
SvelteKitError: Not found: /api/image/serve/88fe51b968fd58d3c333efa60ecdacc5/512x512
    at resolve2 (file:///app/build/server/index.js:4086:18)
    at resolve (file:///app/build/server/index.js:3918:34)
    at Object.handle (file:///app/build/server/chunks/hooks.server-hoE62lsD.js:2:26)
    at respond (file:///app/build/server/index.js:3916:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

I'm not sure how it's fetching the image from Home Assistant, but I assume it's getting a 404 from that and passing it along.

**Comment by notorioustubze** [comment]
I have the same issue in the docker version. The addon version running directly on HA works as expected.

**Comment by maddox** [comment]
I'm using docker as well.

**Comment by Holewijn** [comment]
Ah, its only the docker side of it then, in only running this as Addon*

**Comment by matt8707** [comment]
> It's not cache, as I've set up a local development version and the issue happens there too

[attributes.entity_picture](https://github.com/matt8707/ha-fusion/blob/c5d344c25ab6e7d9dc62b22b423c9a292983b921/src/lib/Components/ComputeIcon.svelte#L485C2-L485C78) should be proxied to your HASS_URL, so you could try to add `/local/pic.png` to ha-fusion url

in dev you need to edit HASS_URL in .env file https://github.com/matt8707/ha-fusion/blob/c5d344c25ab6e7d9dc62b22b423c9a292983b921/.env.example#L4
in docker you need to set HASS_URL env here https://github.com/matt8707/ha-fusion/blob/c5d344c25ab6e7d9dc62b22b423c9a292983b921/docker-compose.yml#L13

If that doesn't work, the only thing I can think of is whitelist_external_dirs or something like that in HA
